plugins {
    id 'java'
}

group = 'org.mollen'
version = 'unspecified'

repositories {
    mavenCentral()
}

dependencies {
    // Kafka
    implementation 'org.springframework.kafka:spring-kafka'

    // Web
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // JPA && Postgres
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'org.postgresql:postgresql'

    // Flyway migrations
    implementation 'org.flywaydb:flyway-core'

    // SSH tool: SSHJ
    implementation 'com.hierynomus:sshj:0.37.0'
}

test {
    useJUnitPlatform()
}