server:
  port: 8080

spring:
  application:
    name: gateway
  graphql:
    graphiql:
      enabled: false
      path: /graphiql

grpc:
  client:
    user-service:
      address: static://${USER_SERVICE_GRPC_HOST}:${USER_SERVICE_GRPC_PORT}
      negotiationType: PLAINTEXT
    stats-service:
      address: static://${STATS_SERVICE_GRPC_HOST}:${STATS_SERVICE_GRPC_PORT}
      negotiationType: PLAINTEXT
