server:
  port: 8080

spring:
  application:
    name: gateway
  graphql:
    graphiql:
      enabled: true
      path: /graphiql

grpc:
  client:
    user_service:
      address:
        'static://${USER_SERVICE_GRPC_HOST:localhost}:${USER_SERVICE_GRPC_PORT:9091}'
      negotiation-type: plaintext
