type Mutation {
    loginWithSteam(openidParamsJson: String!): AuthResponse!
}

type Query {
    # ЗАГЛУШКА
    ping: String!

    getPlayerStats(userId: String!): PlayerStats
}

type AuthResponse {
    userId: String!
    steamId: String!
    isNewUser: Boolean!
    token: String!
}

type PlayerStats {
    eloRating: Int!
    totalPlaytimeHours: Int!
    kills: Int!
    vehiclesDestroyed: Int!
    deaths: Int!
    revives: Int!
    favouriteRole: String!
}


#Clan Service
type ClanMember {
    id: ID!
    userId: String!
    role: String!
}

type Clan {
    id: ID!
    name: String!
    tag: String!
    description: String
    requirements: String
    avatarUrl: String
    isRecruiting: Boolean!
    status: String!
    totalElo: Int!
    minElo: Int!
    createdAt: String!
    members: [ClanMember!]!
}

type CreateClanResponse {
    clanId: ID!
    message: String!
}

type ApplyToClanResponse {
    applicationId: ID!
    message: String!
}

type ProcessAcceptanceResponse {
    newMember: ClanMember
    message: String!
}

extend type Query {
    getClanWithMembers(clanId: ID!): Clan
}

extend type Mutation {
    createClan(
        leaderId: String!,
        name: String!,
        tag: String!,
        description: String,
        requirements: String,
        avatarUrl: String
    ): CreateClanResponse

    applyToClan(
        userId: String!,
        clanId: ID!,
        socialLink: String,
        experienceText: String
    ): ApplyToClanResponse

    processAcceptance(
        applicationId: ID!,
        acceptorId: String!
    ): ProcessAcceptanceResponse
}