// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: internal/core/proto/event.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventService_CreateEvent_FullMethodName          = "/event.EventService/CreateEvent"
	EventService_GetEventsByUserID_FullMethodName    = "/event.EventService/GetEventsByUserID"
	EventService_GetEventsByEventName_FullMethodName = "/event.EventService/GetEventsByEventName"
	EventService_UpdateTimeEvent_FullMethodName      = "/event.EventService/UpdateTimeEvent"
	EventService_DeleteEvent_FullMethodName          = "/event.EventService/DeleteEvent"
	EventService_JoinToEvent_FullMethodName          = "/event.EventService/JoinToEvent"
	EventService_LeaveEvent_FullMethodName           = "/event.EventService/LeaveEvent"
	EventService_CreateGame_FullMethodName           = "/event.EventService/CreateGame"
	EventService_GetGameByID_FullMethodName          = "/event.EventService/GetGameByID"
	EventService_GetGamesByEventID_FullMethodName    = "/event.EventService/GetGamesByEventID"
	EventService_UpdateGameWinner_FullMethodName     = "/event.EventService/UpdateGameWinner"
	EventService_UpdateGameLoser_FullMethodName      = "/event.EventService/UpdateGameLoser"
	EventService_FinishGame_FullMethodName           = "/event.EventService/FinishGame"
	EventService_DeleteGame_FullMethodName           = "/event.EventService/DeleteGame"
	EventService_AddUserStatsToGame_FullMethodName   = "/event.EventService/AddUserStatsToGame"
	EventService_GetGameStats_FullMethodName         = "/event.EventService/GetGameStats"
)

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventServiceClient interface {
	CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*CreateEventResponse, error)
	GetEventsByUserID(ctx context.Context, in *GetEventsByUserIDRequest, opts ...grpc.CallOption) (*GetEventsByUserIDResponse, error)
	GetEventsByEventName(ctx context.Context, in *GetEventsByEventNameRequest, opts ...grpc.CallOption) (*GetEventsByEventNameResponse, error)
	UpdateTimeEvent(ctx context.Context, in *UpdateTimeEventRequest, opts ...grpc.CallOption) (*UpdateTimeEventResponse, error)
	DeleteEvent(ctx context.Context, in *DeleteEventRequest, opts ...grpc.CallOption) (*DeleteEventResponse, error)
	JoinToEvent(ctx context.Context, in *JoinToEventRequest, opts ...grpc.CallOption) (*JoinToEventResponse, error)
	LeaveEvent(ctx context.Context, in *LeaveEventRequest, opts ...grpc.CallOption) (*LeaveEventResponse, error)
	CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*CreateGameResponse, error)
	GetGameByID(ctx context.Context, in *GetGameByIDRequest, opts ...grpc.CallOption) (*GetGameByIDResponse, error)
	GetGamesByEventID(ctx context.Context, in *GetGamesByEventIDRequest, opts ...grpc.CallOption) (*GetGamesByEventIDResponse, error)
	UpdateGameWinner(ctx context.Context, in *UpdateGameWinnerRequest, opts ...grpc.CallOption) (*UpdateGameWinnerResponse, error)
	UpdateGameLoser(ctx context.Context, in *UpdateGameLoserRequest, opts ...grpc.CallOption) (*UpdateGameLoserResponse, error)
	FinishGame(ctx context.Context, in *FinishGameRequest, opts ...grpc.CallOption) (*FinishGameResponse, error)
	DeleteGame(ctx context.Context, in *DeleteGameRequest, opts ...grpc.CallOption) (*DeleteGameResponse, error)
	AddUserStatsToGame(ctx context.Context, in *AddUserStatsToGameRequest, opts ...grpc.CallOption) (*AddUserStatsToGameResponse, error)
	GetGameStats(ctx context.Context, in *GetGameStatsRequest, opts ...grpc.CallOption) (*GetGameStatsResponse, error)
}

type eventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventServiceClient(cc grpc.ClientConnInterface) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*CreateEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEventResponse)
	err := c.cc.Invoke(ctx, EventService_CreateEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetEventsByUserID(ctx context.Context, in *GetEventsByUserIDRequest, opts ...grpc.CallOption) (*GetEventsByUserIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventsByUserIDResponse)
	err := c.cc.Invoke(ctx, EventService_GetEventsByUserID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetEventsByEventName(ctx context.Context, in *GetEventsByEventNameRequest, opts ...grpc.CallOption) (*GetEventsByEventNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventsByEventNameResponse)
	err := c.cc.Invoke(ctx, EventService_GetEventsByEventName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) UpdateTimeEvent(ctx context.Context, in *UpdateTimeEventRequest, opts ...grpc.CallOption) (*UpdateTimeEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTimeEventResponse)
	err := c.cc.Invoke(ctx, EventService_UpdateTimeEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) DeleteEvent(ctx context.Context, in *DeleteEventRequest, opts ...grpc.CallOption) (*DeleteEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEventResponse)
	err := c.cc.Invoke(ctx, EventService_DeleteEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) JoinToEvent(ctx context.Context, in *JoinToEventRequest, opts ...grpc.CallOption) (*JoinToEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinToEventResponse)
	err := c.cc.Invoke(ctx, EventService_JoinToEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) LeaveEvent(ctx context.Context, in *LeaveEventRequest, opts ...grpc.CallOption) (*LeaveEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveEventResponse)
	err := c.cc.Invoke(ctx, EventService_LeaveEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*CreateGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGameResponse)
	err := c.cc.Invoke(ctx, EventService_CreateGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetGameByID(ctx context.Context, in *GetGameByIDRequest, opts ...grpc.CallOption) (*GetGameByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameByIDResponse)
	err := c.cc.Invoke(ctx, EventService_GetGameByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetGamesByEventID(ctx context.Context, in *GetGamesByEventIDRequest, opts ...grpc.CallOption) (*GetGamesByEventIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGamesByEventIDResponse)
	err := c.cc.Invoke(ctx, EventService_GetGamesByEventID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) UpdateGameWinner(ctx context.Context, in *UpdateGameWinnerRequest, opts ...grpc.CallOption) (*UpdateGameWinnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGameWinnerResponse)
	err := c.cc.Invoke(ctx, EventService_UpdateGameWinner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) UpdateGameLoser(ctx context.Context, in *UpdateGameLoserRequest, opts ...grpc.CallOption) (*UpdateGameLoserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGameLoserResponse)
	err := c.cc.Invoke(ctx, EventService_UpdateGameLoser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) FinishGame(ctx context.Context, in *FinishGameRequest, opts ...grpc.CallOption) (*FinishGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinishGameResponse)
	err := c.cc.Invoke(ctx, EventService_FinishGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) DeleteGame(ctx context.Context, in *DeleteGameRequest, opts ...grpc.CallOption) (*DeleteGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteGameResponse)
	err := c.cc.Invoke(ctx, EventService_DeleteGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) AddUserStatsToGame(ctx context.Context, in *AddUserStatsToGameRequest, opts ...grpc.CallOption) (*AddUserStatsToGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddUserStatsToGameResponse)
	err := c.cc.Invoke(ctx, EventService_AddUserStatsToGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetGameStats(ctx context.Context, in *GetGameStatsRequest, opts ...grpc.CallOption) (*GetGameStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameStatsResponse)
	err := c.cc.Invoke(ctx, EventService_GetGameStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServiceServer is the server API for EventService service.
// All implementations must embed UnimplementedEventServiceServer
// for forward compatibility.
type EventServiceServer interface {
	CreateEvent(context.Context, *CreateEventRequest) (*CreateEventResponse, error)
	GetEventsByUserID(context.Context, *GetEventsByUserIDRequest) (*GetEventsByUserIDResponse, error)
	GetEventsByEventName(context.Context, *GetEventsByEventNameRequest) (*GetEventsByEventNameResponse, error)
	UpdateTimeEvent(context.Context, *UpdateTimeEventRequest) (*UpdateTimeEventResponse, error)
	DeleteEvent(context.Context, *DeleteEventRequest) (*DeleteEventResponse, error)
	JoinToEvent(context.Context, *JoinToEventRequest) (*JoinToEventResponse, error)
	LeaveEvent(context.Context, *LeaveEventRequest) (*LeaveEventResponse, error)
	CreateGame(context.Context, *CreateGameRequest) (*CreateGameResponse, error)
	GetGameByID(context.Context, *GetGameByIDRequest) (*GetGameByIDResponse, error)
	GetGamesByEventID(context.Context, *GetGamesByEventIDRequest) (*GetGamesByEventIDResponse, error)
	UpdateGameWinner(context.Context, *UpdateGameWinnerRequest) (*UpdateGameWinnerResponse, error)
	UpdateGameLoser(context.Context, *UpdateGameLoserRequest) (*UpdateGameLoserResponse, error)
	FinishGame(context.Context, *FinishGameRequest) (*FinishGameResponse, error)
	DeleteGame(context.Context, *DeleteGameRequest) (*DeleteGameResponse, error)
	AddUserStatsToGame(context.Context, *AddUserStatsToGameRequest) (*AddUserStatsToGameResponse, error)
	GetGameStats(context.Context, *GetGameStatsRequest) (*GetGameStatsResponse, error)
	mustEmbedUnimplementedEventServiceServer()
}

// UnimplementedEventServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventServiceServer struct{}

func (UnimplementedEventServiceServer) CreateEvent(context.Context, *CreateEventRequest) (*CreateEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEvent not implemented")
}
func (UnimplementedEventServiceServer) GetEventsByUserID(context.Context, *GetEventsByUserIDRequest) (*GetEventsByUserIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventsByUserID not implemented")
}
func (UnimplementedEventServiceServer) GetEventsByEventName(context.Context, *GetEventsByEventNameRequest) (*GetEventsByEventNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventsByEventName not implemented")
}
func (UnimplementedEventServiceServer) UpdateTimeEvent(context.Context, *UpdateTimeEventRequest) (*UpdateTimeEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTimeEvent not implemented")
}
func (UnimplementedEventServiceServer) DeleteEvent(context.Context, *DeleteEventRequest) (*DeleteEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEvent not implemented")
}
func (UnimplementedEventServiceServer) JoinToEvent(context.Context, *JoinToEventRequest) (*JoinToEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinToEvent not implemented")
}
func (UnimplementedEventServiceServer) LeaveEvent(context.Context, *LeaveEventRequest) (*LeaveEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaveEvent not implemented")
}
func (UnimplementedEventServiceServer) CreateGame(context.Context, *CreateGameRequest) (*CreateGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGame not implemented")
}
func (UnimplementedEventServiceServer) GetGameByID(context.Context, *GetGameByIDRequest) (*GetGameByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGameByID not implemented")
}
func (UnimplementedEventServiceServer) GetGamesByEventID(context.Context, *GetGamesByEventIDRequest) (*GetGamesByEventIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGamesByEventID not implemented")
}
func (UnimplementedEventServiceServer) UpdateGameWinner(context.Context, *UpdateGameWinnerRequest) (*UpdateGameWinnerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGameWinner not implemented")
}
func (UnimplementedEventServiceServer) UpdateGameLoser(context.Context, *UpdateGameLoserRequest) (*UpdateGameLoserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGameLoser not implemented")
}
func (UnimplementedEventServiceServer) FinishGame(context.Context, *FinishGameRequest) (*FinishGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FinishGame not implemented")
}
func (UnimplementedEventServiceServer) DeleteGame(context.Context, *DeleteGameRequest) (*DeleteGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteGame not implemented")
}
func (UnimplementedEventServiceServer) AddUserStatsToGame(context.Context, *AddUserStatsToGameRequest) (*AddUserStatsToGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddUserStatsToGame not implemented")
}
func (UnimplementedEventServiceServer) GetGameStats(context.Context, *GetGameStatsRequest) (*GetGameStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGameStats not implemented")
}
func (UnimplementedEventServiceServer) mustEmbedUnimplementedEventServiceServer() {}
func (UnimplementedEventServiceServer) testEmbeddedByValue()                      {}

// UnsafeEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventServiceServer will
// result in compilation errors.
type UnsafeEventServiceServer interface {
	mustEmbedUnimplementedEventServiceServer()
}

func RegisterEventServiceServer(s grpc.ServiceRegistrar, srv EventServiceServer) {
	// If the following call panics, it indicates UnimplementedEventServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventService_ServiceDesc, srv)
}

func _EventService_CreateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).CreateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_CreateEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).CreateEvent(ctx, req.(*CreateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetEventsByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetEventsByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetEventsByUserID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetEventsByUserID(ctx, req.(*GetEventsByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetEventsByEventName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsByEventNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetEventsByEventName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetEventsByEventName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetEventsByEventName(ctx, req.(*GetEventsByEventNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_UpdateTimeEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTimeEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).UpdateTimeEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_UpdateTimeEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).UpdateTimeEvent(ctx, req.(*UpdateTimeEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_DeleteEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).DeleteEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_DeleteEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).DeleteEvent(ctx, req.(*DeleteEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_JoinToEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinToEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).JoinToEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_JoinToEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).JoinToEvent(ctx, req.(*JoinToEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_LeaveEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).LeaveEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_LeaveEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).LeaveEvent(ctx, req.(*LeaveEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_CreateGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).CreateGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_CreateGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).CreateGame(ctx, req.(*CreateGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetGameByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetGameByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetGameByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetGameByID(ctx, req.(*GetGameByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetGamesByEventID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGamesByEventIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetGamesByEventID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetGamesByEventID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetGamesByEventID(ctx, req.(*GetGamesByEventIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_UpdateGameWinner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGameWinnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).UpdateGameWinner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_UpdateGameWinner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).UpdateGameWinner(ctx, req.(*UpdateGameWinnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_UpdateGameLoser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGameLoserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).UpdateGameLoser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_UpdateGameLoser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).UpdateGameLoser(ctx, req.(*UpdateGameLoserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_FinishGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).FinishGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_FinishGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).FinishGame(ctx, req.(*FinishGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_DeleteGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).DeleteGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_DeleteGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).DeleteGame(ctx, req.(*DeleteGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_AddUserStatsToGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserStatsToGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).AddUserStatsToGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_AddUserStatsToGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).AddUserStatsToGame(ctx, req.(*AddUserStatsToGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetGameStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetGameStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetGameStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetGameStats(ctx, req.(*GetGameStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventService_ServiceDesc is the grpc.ServiceDesc for EventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "event.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEvent",
			Handler:    _EventService_CreateEvent_Handler,
		},
		{
			MethodName: "GetEventsByUserID",
			Handler:    _EventService_GetEventsByUserID_Handler,
		},
		{
			MethodName: "GetEventsByEventName",
			Handler:    _EventService_GetEventsByEventName_Handler,
		},
		{
			MethodName: "UpdateTimeEvent",
			Handler:    _EventService_UpdateTimeEvent_Handler,
		},
		{
			MethodName: "DeleteEvent",
			Handler:    _EventService_DeleteEvent_Handler,
		},
		{
			MethodName: "JoinToEvent",
			Handler:    _EventService_JoinToEvent_Handler,
		},
		{
			MethodName: "LeaveEvent",
			Handler:    _EventService_LeaveEvent_Handler,
		},
		{
			MethodName: "CreateGame",
			Handler:    _EventService_CreateGame_Handler,
		},
		{
			MethodName: "GetGameByID",
			Handler:    _EventService_GetGameByID_Handler,
		},
		{
			MethodName: "GetGamesByEventID",
			Handler:    _EventService_GetGamesByEventID_Handler,
		},
		{
			MethodName: "UpdateGameWinner",
			Handler:    _EventService_UpdateGameWinner_Handler,
		},
		{
			MethodName: "UpdateGameLoser",
			Handler:    _EventService_UpdateGameLoser_Handler,
		},
		{
			MethodName: "FinishGame",
			Handler:    _EventService_FinishGame_Handler,
		},
		{
			MethodName: "DeleteGame",
			Handler:    _EventService_DeleteGame_Handler,
		},
		{
			MethodName: "AddUserStatsToGame",
			Handler:    _EventService_AddUserStatsToGame_Handler,
		},
		{
			MethodName: "GetGameStats",
			Handler:    _EventService_GetGameStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/core/proto/event.proto",
}
