syntax = "proto3";

package event;

option go_package = "event-service/internal/core/proto";

import "google/protobuf/timestamp.proto";

service EventService {
    rpc CreateEvent(CreateEventRequest) returns (CreateEventResponse);
    rpc GetEventsByUserID(GetEventsByUserIDRequest) returns (GetEventsByUserIDResponse);
    rpc GetEventsByEventName(GetEventsByEventNameRequest) returns (GetEventsByEventNameResponse);
    rpc GetUnfinishedEventsByUserID(GetUnfinishedEventsByUserIDRequest) returns (GetUnfinishedEventsByUserIDResponse);
    rpc GetUnfinishedEventsByEventName(GetUnfinishedEventsByEventNameRequest) returns (GetUnfinishedEventsByEventNameResponse);
    rpc UpdateTimeEvent(UpdateTimeEventRequest) returns (UpdateTimeEventResponse);
    rpc DeleteEvent(DeleteEventRequest) returns (DeleteEventResponse);
    rpc JoinToEvent(JoinToEventRequest) returns (JoinToEventResponse);
    rpc LeaveEvent(LeaveEventRequest) returns (LeaveEventResponse);
    rpc SetRole(SetRoleRequest) returns (SetRoleResponse);
    rpc CreateTeamsForEvent(CreateTeamsForEventRequest) returns (CreateTeamsForEventResponse);
    rpc GetTeamsByEventID(GetTeamsByEventIDRequest) returns (GetTeamsByEventIDResponse);
    rpc StartEvent(StartEventRequest) returns (StartEventResponse);
    rpc FinishEvent(FinishEventRequest) returns (FinishEventResponse);
    rpc CreateGame(CreateGameRequest) returns (CreateGameResponse);
    rpc GetGameByID(GetGameByIDRequest) returns (GetGameByIDResponse);
    rpc GetGamesByEventID(GetGamesByEventIDRequest) returns (GetGamesByEventIDResponse);
    rpc UpdateGameWinner(UpdateGameWinnerRequest) returns (UpdateGameWinnerResponse);
    rpc UpdateGameLoser(UpdateGameLoserRequest) returns (UpdateGameLoserResponse);
    rpc FinishGame(FinishGameRequest) returns (FinishGameResponse);
    rpc DeleteGame(DeleteGameRequest) returns (DeleteGameResponse);
    rpc AddUserStatsToGame(AddUserStatsToGameRequest) returns (AddUserStatsToGameResponse);
    rpc GetGameStats(GetGameStatsRequest) returns (GetGameStatsResponse);
    rpc GetTeamByID(GetTeamByIDRequest) returns (GetTeamByIDResponse);
    rpc AddUserToTeam(AddUserToTeamRequest) returns (AddUserToTeamResponse);
    rpc RemoveUserFromTeam(RemoveUserFromTeamRequest) returns (RemoveUserFromTeamResponse);
}

message Event {
    string event_id = 1;
    string name = 2;
    string user_create_id = 3;
    string enemy_side_leader = 4;
    int64 user_count = 5;
    google.protobuf.Timestamp time_start = 6;
    google.protobuf.Timestamp time_finish = 7;
    google.protobuf.Timestamp create_time = 8;
    string event_team_winner = 9;
    string event_team_loser = 10;
    bool is_confirmed = 11;
    bool is_started = 12;
    bool is_finished = 13;
}

message User {
    string user_event_id = 1;
    string user_id = 2;
    string clan_id = 3;
    string team_id = 4;
    string role = 5;
    bool six_clan_members = 6;
}

message Game {
    string game_id = 1;
    string event_id = 2;
    string user_create_id = 3;
    string enemy_side_leader = 4;
    string team1_id = 5;
    string team2_id = 6;
    string map_name = 7;
    string game_team_winner_id = 8;
    string game_team_loser_id = 9;
    google.protobuf.Timestamp time_start = 10;
    google.protobuf.Timestamp time_finish = 11;
}

message Team {
    string team_id = 1;
    string event_id = 2;
    string side_leader_id = 3;
    bool is_confirmed = 4;
    repeated User members = 5;
}

message GameUserStats {
    string game_user_stats_id = 1;
    Game game = 2;
    User user = 3;
    int64 kills = 4;
    int64 deaths = 5;
    int64 points = 6;
}

message CreateEventRequest {
    string user_create_id = 1;
    string enemy_side_leader = 2;
    string event_name = 3;
    google.protobuf.Timestamp time_start = 4;
}

message CreateEventResponse {
    string error = 1;
}

message GetEventsByUserIDRequest {
    string user_create_id = 1;
}

message GetEventsByUserIDResponse {
    repeated Event events = 1;
    string error = 2;
}

message GetEventsByEventNameRequest {
    string event_name = 1;
}

message GetEventsByEventNameResponse {
    repeated Event events = 1;
    string error = 2;
}

message UpdateTimeEventRequest {
    string event_id = 1;
    string user_create_id = 2;
    google.protobuf.Timestamp new_time_start = 3;
}

message UpdateTimeEventResponse {
    string error = 1;
}

message DeleteEventRequest {
    string event_id = 1;
    string user_create_id = 2;
}

message DeleteEventResponse {
    string error = 1;
}

message JoinToEventRequest {
    string event_id = 1;
    string user_id = 2;
    google.protobuf.Timestamp join_time = 3;
}

message JoinToEventResponse {
    string error = 1;
}

message LeaveEventRequest {
    string user_id = 1;
    string event_id = 2;
}

message LeaveEventResponse {
    string error = 1;
}

message SetRoleRequest {
    string event_id = 1;
    string side_leader_id = 2;
    string user_id = 3;
    string role = 4;
}

message SetRoleResponse {
    string error = 1;
}

message CreateTeamsForEventRequest {
    string event_id = 1;
}

message CreateTeamsForEventResponse {
    string error = 1;
}

message GetTeamsByEventIDRequest {
    string event_id = 1;
}

message GetTeamsByEventIDResponse {
    repeated Team teams = 1;
    string error = 2;
}

message StartEventRequest {
    string event_id = 1;
    string side_leader_id = 2;
}

message StartEventResponse {
    string error = 1;
}

message CreateGameRequest {
    string event_id = 1;
    string map_name = 2;
    google.protobuf.Timestamp time_start = 3;
}

message CreateGameResponse {
    string error = 1;
}

message GetGameByIDRequest {
    string game_id = 1;
}

message GetGameByIDResponse {
    Game game = 1;
    string error = 2;
}

message GetGamesByEventIDRequest {
    string event_id = 1;
}

message GetGamesByEventIDResponse {
    repeated Game games = 1;
    string error = 2;
}

message UpdateGameWinnerRequest {
    string game_id = 1;
    string winner_team_id = 2;
}

message UpdateGameWinnerResponse {
    string error = 1;
}

message UpdateGameLoserRequest {
    string game_id = 1;
    string loser_team_id = 2;
}

message UpdateGameLoserResponse {
    string error = 1;
}

message FinishGameRequest {
    string game_id = 1;
    google.protobuf.Timestamp time_finish = 2;
}

message FinishGameResponse {
    string error = 1;
}

message DeleteGameRequest {
    string game_id = 1;
}

message DeleteGameResponse {
    string error = 1;
}

message AddUserStatsToGameRequest {
    string game_id = 1;
    string user_id = 2;
    int64 kills = 3;
    int64 deaths = 4;
    int64 points = 5;
}

message AddUserStatsToGameResponse {
    string error = 1;
}

message GetGameStatsRequest {
    string game_id = 1;
}

message GetGameStatsResponse {
    repeated GameUserStats stats = 1;
    string error = 2;
}

message GetTeamByIDRequest {
    string team_id = 1;
}

message GetTeamByIDResponse {
    Team team = 1;
    string error = 2;
}

message AddUserToTeamRequest {
    string team_id = 1;
    string user_id = 2;
    string clan_id = 3;
    string role = 4;
}

message AddUserToTeamResponse {
    string error = 1;
}

message RemoveUserFromTeamRequest {
    string team_id = 1;
    string user_id = 2;
}

message RemoveUserFromTeamResponse {
    string error = 1;
}

message GetUnfinishedEventsByUserIDRequest {
    string user_create_id = 1;
}

message GetUnfinishedEventsByUserIDResponse {
    repeated Event events = 1;
    string error = 2;
}

message GetUnfinishedEventsByEventNameRequest {
    string event_name = 1;
}

message GetUnfinishedEventsByEventNameResponse {
    repeated Event events = 1;
    string error = 2;
}

message FinishEventRequest {
    string event_id = 1;
    string user_create_id = 2;
}

message FinishEventResponse {
    string error = 1;
}
