// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: event.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EventId           string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventName         string                 `protobuf:"bytes,2,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	UserCreateId      string                 `protobuf:"bytes,3,opt,name=user_create_id,json=userCreateId,proto3" json:"user_create_id,omitempty"`
	EnemySideLeaderId string                 `protobuf:"bytes,4,opt,name=enemy_side_leader_id,json=enemySideLeaderId,proto3" json:"enemy_side_leader_id,omitempty"`
	UserCount         int64                  `protobuf:"varint,5,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
	TimeStart         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"`
	TimeFinish        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=time_finish,json=timeFinish,proto3" json:"time_finish,omitempty"`
	CreateTime        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// "" | "ally" | "enemy" | "draw"
	WinnerSide      string `protobuf:"bytes,9,opt,name=winner_side,json=winnerSide,proto3" json:"winner_side,omitempty"`
	TargetGameCount int64  `protobuf:"varint,12,opt,name=target_game_count,json=targetGameCount,proto3" json:"target_game_count,omitempty"`
	GameCount       int64  `protobuf:"varint,13,opt,name=game_count,json=gameCount,proto3" json:"game_count,omitempty"`
	// pending | confirmed | in_progress | finished | declined | canceled
	Status        string `protobuf:"bytes,14,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *Event) GetUserCreateId() string {
	if x != nil {
		return x.UserCreateId
	}
	return ""
}

func (x *Event) GetEnemySideLeaderId() string {
	if x != nil {
		return x.EnemySideLeaderId
	}
	return ""
}

func (x *Event) GetUserCount() int64 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

func (x *Event) GetTimeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeStart
	}
	return nil
}

func (x *Event) GetTimeFinish() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeFinish
	}
	return nil
}

func (x *Event) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Event) GetWinnerSide() string {
	if x != nil {
		return x.WinnerSide
	}
	return ""
}

func (x *Event) GetTargetGameCount() int64 {
	if x != nil {
		return x.TargetGameCount
	}
	return 0
}

func (x *Event) GetGameCount() int64 {
	if x != nil {
		return x.GameCount
	}
	return 0
}

func (x *Event) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserEventId   string                 `protobuf:"bytes,1,opt,name=user_event_id,json=userEventId,proto3" json:"user_event_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventId       string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	ClanId        string                 `protobuf:"bytes,4,opt,name=clan_id,json=clanId,proto3" json:"clan_id,omitempty"`
	Enemy         bool                   `protobuf:"varint,5,opt,name=enemy,proto3" json:"enemy,omitempty"`
	Role          string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	JoinTime      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=join_time,json=joinTime,proto3" json:"join_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetUserEventId() string {
	if x != nil {
		return x.UserEventId
	}
	return ""
}

func (x *User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *User) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *User) GetClanId() string {
	if x != nil {
		return x.ClanId
	}
	return ""
}

func (x *User) GetEnemy() bool {
	if x != nil {
		return x.Enemy
	}
	return false
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetJoinTime() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinTime
	}
	return nil
}

type Team struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TeamId                 string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	EventId                string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SideLeaderId           string                 `protobuf:"bytes,3,opt,name=side_leader_id,json=sideLeaderId,proto3" json:"side_leader_id,omitempty"`
	GameNumber             int64                  `protobuf:"varint,4,opt,name=game_number,json=gameNumber,proto3" json:"game_number,omitempty"`
	MembersCount           int64                  `protobuf:"varint,5,opt,name=members_count,json=membersCount,proto3" json:"members_count,omitempty"`
	Winner                 bool                   `protobuf:"varint,6,opt,name=winner,proto3" json:"winner,omitempty"`
	TotalKills             int64                  `protobuf:"varint,7,opt,name=total_kills,json=totalKills,proto3" json:"total_kills,omitempty"`
	TotalDeaths            int64                  `protobuf:"varint,8,opt,name=total_deaths,json=totalDeaths,proto3" json:"total_deaths,omitempty"`
	TotalPoints            int64                  `protobuf:"varint,9,opt,name=total_points,json=totalPoints,proto3" json:"total_points,omitempty"`
	TotalRevival           int64                  `protobuf:"varint,10,opt,name=total_revival,json=totalRevival,proto3" json:"total_revival,omitempty"`
	TotalDestroyedVehicles int64                  `protobuf:"varint,11,opt,name=total_destroyed_vehicles,json=totalDestroyedVehicles,proto3" json:"total_destroyed_vehicles,omitempty"`
	// Пустой time_start => игра ещё не началась. Пустой time_finish => игра ещё не окончена.
	TimeStart     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"`
	TimeFinish    *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=time_finish,json=timeFinish,proto3" json:"time_finish,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Team) Reset() {
	*x = Team{}
	mi := &file_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Team) ProtoMessage() {}

func (x *Team) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Team.ProtoReflect.Descriptor instead.
func (*Team) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{2}
}

func (x *Team) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *Team) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Team) GetSideLeaderId() string {
	if x != nil {
		return x.SideLeaderId
	}
	return ""
}

func (x *Team) GetGameNumber() int64 {
	if x != nil {
		return x.GameNumber
	}
	return 0
}

func (x *Team) GetMembersCount() int64 {
	if x != nil {
		return x.MembersCount
	}
	return 0
}

func (x *Team) GetWinner() bool {
	if x != nil {
		return x.Winner
	}
	return false
}

func (x *Team) GetTotalKills() int64 {
	if x != nil {
		return x.TotalKills
	}
	return 0
}

func (x *Team) GetTotalDeaths() int64 {
	if x != nil {
		return x.TotalDeaths
	}
	return 0
}

func (x *Team) GetTotalPoints() int64 {
	if x != nil {
		return x.TotalPoints
	}
	return 0
}

func (x *Team) GetTotalRevival() int64 {
	if x != nil {
		return x.TotalRevival
	}
	return 0
}

func (x *Team) GetTotalDestroyedVehicles() int64 {
	if x != nil {
		return x.TotalDestroyedVehicles
	}
	return 0
}

func (x *Team) GetTimeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeStart
	}
	return nil
}

func (x *Team) GetTimeFinish() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeFinish
	}
	return nil
}

type TeamMember struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TeamId            string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	UserEventId       string                 `protobuf:"bytes,2,opt,name=user_event_id,json=userEventId,proto3" json:"user_event_id,omitempty"`
	UserId            string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role              string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Kills             int64                  `protobuf:"varint,5,opt,name=kills,proto3" json:"kills,omitempty"`
	Deaths            int64                  `protobuf:"varint,6,opt,name=deaths,proto3" json:"deaths,omitempty"`
	Points            int64                  `protobuf:"varint,7,opt,name=points,proto3" json:"points,omitempty"`
	Revival           int64                  `protobuf:"varint,8,opt,name=revival,proto3" json:"revival,omitempty"`
	DestroyedVehicles int64                  `protobuf:"varint,9,opt,name=destroyed_vehicles,json=destroyedVehicles,proto3" json:"destroyed_vehicles,omitempty"`
	// Сигнал для другого микросервиса: перед стартом игры он смотрит на этот
	// флаг у каждого участника команды и решает, приглашать его (true) или
	// проигнорировать (false). Считается по клану внутри команды, не по
	// всему ивенту (см. JoinUserToTeam).
	SixClanMembers bool `protobuf:"varint,10,opt,name=six_clan_members,json=sixClanMembers,proto3" json:"six_clan_members,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TeamMember) Reset() {
	*x = TeamMember{}
	mi := &file_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamMember) ProtoMessage() {}

func (x *TeamMember) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamMember.ProtoReflect.Descriptor instead.
func (*TeamMember) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{3}
}

func (x *TeamMember) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *TeamMember) GetUserEventId() string {
	if x != nil {
		return x.UserEventId
	}
	return ""
}

func (x *TeamMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TeamMember) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *TeamMember) GetKills() int64 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *TeamMember) GetDeaths() int64 {
	if x != nil {
		return x.Deaths
	}
	return 0
}

func (x *TeamMember) GetPoints() int64 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *TeamMember) GetRevival() int64 {
	if x != nil {
		return x.Revival
	}
	return 0
}

func (x *TeamMember) GetDestroyedVehicles() int64 {
	if x != nil {
		return x.DestroyedVehicles
	}
	return 0
}

func (x *TeamMember) GetSixClanMembers() bool {
	if x != nil {
		return x.SixClanMembers
	}
	return false
}

type GetEventMembersListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventMembersListRequest) Reset() {
	*x = GetEventMembersListRequest{}
	mi := &file_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventMembersListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventMembersListRequest) ProtoMessage() {}

func (x *GetEventMembersListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventMembersListRequest.ProtoReflect.Descriptor instead.
func (*GetEventMembersListRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{4}
}

func (x *GetEventMembersListRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type GetEventMembersListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventMembersListResponse) Reset() {
	*x = GetEventMembersListResponse{}
	mi := &file_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventMembersListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventMembersListResponse) ProtoMessage() {}

func (x *GetEventMembersListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventMembersListResponse.ProtoReflect.Descriptor instead.
func (*GetEventMembersListResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{5}
}

func (x *GetEventMembersListResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *GetEventMembersListResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CreateEventRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	UserCreatorId         string                 `protobuf:"bytes,1,opt,name=user_creator_id,json=userCreatorId,proto3" json:"user_creator_id,omitempty"`
	CreatorClanId         string                 `protobuf:"bytes,2,opt,name=creator_clan_id,json=creatorClanId,proto3" json:"creator_clan_id,omitempty"`
	EnemySideLeaderId     string                 `protobuf:"bytes,3,opt,name=enemy_side_leader_id,json=enemySideLeaderId,proto3" json:"enemy_side_leader_id,omitempty"`
	EnemySideLeaderClanId string                 `protobuf:"bytes,4,opt,name=enemy_side_leader_clan_id,json=enemySideLeaderClanId,proto3" json:"enemy_side_leader_clan_id,omitempty"`
	EventName             string                 `protobuf:"bytes,5,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	TimeStart             *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"`
	// Сколько игр сыграть в рамках ивента: 1, 2 или 3.
	TargetGameCount int64 `protobuf:"varint,7,opt,name=target_game_count,json=targetGameCount,proto3" json:"target_game_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{6}
}

func (x *CreateEventRequest) GetUserCreatorId() string {
	if x != nil {
		return x.UserCreatorId
	}
	return ""
}

func (x *CreateEventRequest) GetCreatorClanId() string {
	if x != nil {
		return x.CreatorClanId
	}
	return ""
}

func (x *CreateEventRequest) GetEnemySideLeaderId() string {
	if x != nil {
		return x.EnemySideLeaderId
	}
	return ""
}

func (x *CreateEventRequest) GetEnemySideLeaderClanId() string {
	if x != nil {
		return x.EnemySideLeaderClanId
	}
	return ""
}

func (x *CreateEventRequest) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *CreateEventRequest) GetTimeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeStart
	}
	return nil
}

func (x *CreateEventRequest) GetTargetGameCount() int64 {
	if x != nil {
		return x.TargetGameCount
	}
	return 0
}

type CreateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventResponse) Reset() {
	*x = CreateEventResponse{}
	mi := &file_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventResponse) ProtoMessage() {}

func (x *CreateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventResponse.ProtoReflect.Descriptor instead.
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{7}
}

func (x *CreateEventResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetEventsByCreatorIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserCreateId  string                 `protobuf:"bytes,1,opt,name=user_create_id,json=userCreateId,proto3" json:"user_create_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsByCreatorIdRequest) Reset() {
	*x = GetEventsByCreatorIdRequest{}
	mi := &file_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsByCreatorIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsByCreatorIdRequest) ProtoMessage() {}

func (x *GetEventsByCreatorIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsByCreatorIdRequest.ProtoReflect.Descriptor instead.
func (*GetEventsByCreatorIdRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{8}
}

func (x *GetEventsByCreatorIdRequest) GetUserCreateId() string {
	if x != nil {
		return x.UserCreateId
	}
	return ""
}

type GetEventsByCreatorIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsByCreatorIdResponse) Reset() {
	*x = GetEventsByCreatorIdResponse{}
	mi := &file_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsByCreatorIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsByCreatorIdResponse) ProtoMessage() {}

func (x *GetEventsByCreatorIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsByCreatorIdResponse.ProtoReflect.Descriptor instead.
func (*GetEventsByCreatorIdResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{9}
}

func (x *GetEventsByCreatorIdResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetEventsByCreatorIdResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetLastEventByCreatorIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserCreateId  string                 `protobuf:"bytes,1,opt,name=user_create_id,json=userCreateId,proto3" json:"user_create_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastEventByCreatorIdRequest) Reset() {
	*x = GetLastEventByCreatorIdRequest{}
	mi := &file_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastEventByCreatorIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastEventByCreatorIdRequest) ProtoMessage() {}

func (x *GetLastEventByCreatorIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastEventByCreatorIdRequest.ProtoReflect.Descriptor instead.
func (*GetLastEventByCreatorIdRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{10}
}

func (x *GetLastEventByCreatorIdRequest) GetUserCreateId() string {
	if x != nil {
		return x.UserCreateId
	}
	return ""
}

type GetLastEventByCreatorIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastEventByCreatorIdResponse) Reset() {
	*x = GetLastEventByCreatorIdResponse{}
	mi := &file_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastEventByCreatorIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastEventByCreatorIdResponse) ProtoMessage() {}

func (x *GetLastEventByCreatorIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastEventByCreatorIdResponse.ProtoReflect.Descriptor instead.
func (*GetLastEventByCreatorIdResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{11}
}

func (x *GetLastEventByCreatorIdResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *GetLastEventByCreatorIdResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetEventsByEventNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventName     string                 `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsByEventNameRequest) Reset() {
	*x = GetEventsByEventNameRequest{}
	mi := &file_event_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsByEventNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsByEventNameRequest) ProtoMessage() {}

func (x *GetEventsByEventNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsByEventNameRequest.ProtoReflect.Descriptor instead.
func (*GetEventsByEventNameRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{12}
}

func (x *GetEventsByEventNameRequest) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

type GetEventsByEventNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsByEventNameResponse) Reset() {
	*x = GetEventsByEventNameResponse{}
	mi := &file_event_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsByEventNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsByEventNameResponse) ProtoMessage() {}

func (x *GetEventsByEventNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsByEventNameResponse.ProtoReflect.Descriptor instead.
func (*GetEventsByEventNameResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{13}
}

func (x *GetEventsByEventNameResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetEventsByEventNameResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateTimeEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserCreateId  string                 `protobuf:"bytes,2,opt,name=user_create_id,json=userCreateId,proto3" json:"user_create_id,omitempty"`
	NewTimeStart  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=new_time_start,json=newTimeStart,proto3" json:"new_time_start,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTimeEventRequest) Reset() {
	*x = UpdateTimeEventRequest{}
	mi := &file_event_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTimeEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTimeEventRequest) ProtoMessage() {}

func (x *UpdateTimeEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTimeEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateTimeEventRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateTimeEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *UpdateTimeEventRequest) GetUserCreateId() string {
	if x != nil {
		return x.UserCreateId
	}
	return ""
}

func (x *UpdateTimeEventRequest) GetNewTimeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.NewTimeStart
	}
	return nil
}

type UpdateTimeEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTimeEventResponse) Reset() {
	*x = UpdateTimeEventResponse{}
	mi := &file_event_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTimeEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTimeEventResponse) ProtoMessage() {}

func (x *UpdateTimeEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTimeEventResponse.ProtoReflect.Descriptor instead.
func (*UpdateTimeEventResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateTimeEventResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// CancelEvent — ручная отмена ивента создателем (пока он ещё pending или
// confirmed). Статус становится "canceled" — в отличие от "declined", в
// который автоматически уходит ивент, не набравший минимум игроков к
// контрольной точке (см. controlEventTimerDenial).
type CancelEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserCreateId  string                 `protobuf:"bytes,2,opt,name=user_create_id,json=userCreateId,proto3" json:"user_create_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelEventRequest) Reset() {
	*x = CancelEventRequest{}
	mi := &file_event_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelEventRequest) ProtoMessage() {}

func (x *CancelEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelEventRequest.ProtoReflect.Descriptor instead.
func (*CancelEventRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{16}
}

func (x *CancelEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CancelEventRequest) GetUserCreateId() string {
	if x != nil {
		return x.UserCreateId
	}
	return ""
}

type CancelEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelEventResponse) Reset() {
	*x = CancelEventResponse{}
	mi := &file_event_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelEventResponse) ProtoMessage() {}

func (x *CancelEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelEventResponse.ProtoReflect.Descriptor instead.
func (*CancelEventResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{17}
}

func (x *CancelEventResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type JoinToEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClanId        string                 `protobuf:"bytes,3,opt,name=clan_id,json=clanId,proto3" json:"clan_id,omitempty"`
	Enemy         bool                   `protobuf:"varint,4,opt,name=enemy,proto3" json:"enemy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinToEventRequest) Reset() {
	*x = JoinToEventRequest{}
	mi := &file_event_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinToEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinToEventRequest) ProtoMessage() {}

func (x *JoinToEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinToEventRequest.ProtoReflect.Descriptor instead.
func (*JoinToEventRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{18}
}

func (x *JoinToEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *JoinToEventRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JoinToEventRequest) GetClanId() string {
	if x != nil {
		return x.ClanId
	}
	return ""
}

func (x *JoinToEventRequest) GetEnemy() bool {
	if x != nil {
		return x.Enemy
	}
	return false
}

type JoinToEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinToEventResponse) Reset() {
	*x = JoinToEventResponse{}
	mi := &file_event_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinToEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinToEventResponse) ProtoMessage() {}

func (x *JoinToEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinToEventResponse.ProtoReflect.Descriptor instead.
func (*JoinToEventResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{19}
}

func (x *JoinToEventResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LeaveEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveEventRequest) Reset() {
	*x = LeaveEventRequest{}
	mi := &file_event_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveEventRequest) ProtoMessage() {}

func (x *LeaveEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveEventRequest.ProtoReflect.Descriptor instead.
func (*LeaveEventRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{20}
}

func (x *LeaveEventRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LeaveEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type LeaveEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveEventResponse) Reset() {
	*x = LeaveEventResponse{}
	mi := &file_event_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveEventResponse) ProtoMessage() {}

func (x *LeaveEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveEventResponse.ProtoReflect.Descriptor instead.
func (*LeaveEventResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{21}
}

func (x *LeaveEventResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SetRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SideLeaderId  string                 `protobuf:"bytes,2,opt,name=side_leader_id,json=sideLeaderId,proto3" json:"side_leader_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRoleRequest) Reset() {
	*x = SetRoleRequest{}
	mi := &file_event_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRoleRequest) ProtoMessage() {}

func (x *SetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRoleRequest.ProtoReflect.Descriptor instead.
func (*SetRoleRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{22}
}

func (x *SetRoleRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *SetRoleRequest) GetSideLeaderId() string {
	if x != nil {
		return x.SideLeaderId
	}
	return ""
}

func (x *SetRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type SetRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRoleResponse) Reset() {
	*x = SetRoleResponse{}
	mi := &file_event_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRoleResponse) ProtoMessage() {}

func (x *SetRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRoleResponse.ProtoReflect.Descriptor instead.
func (*SetRoleResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{23}
}

func (x *SetRoleResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetTeamsByEventIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamsByEventIDRequest) Reset() {
	*x = GetTeamsByEventIDRequest{}
	mi := &file_event_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamsByEventIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamsByEventIDRequest) ProtoMessage() {}

func (x *GetTeamsByEventIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamsByEventIDRequest.ProtoReflect.Descriptor instead.
func (*GetTeamsByEventIDRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{24}
}

func (x *GetTeamsByEventIDRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type GetTeamsByEventIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teams         []*Team                `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamsByEventIDResponse) Reset() {
	*x = GetTeamsByEventIDResponse{}
	mi := &file_event_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamsByEventIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamsByEventIDResponse) ProtoMessage() {}

func (x *GetTeamsByEventIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamsByEventIDResponse.ProtoReflect.Descriptor instead.
func (*GetTeamsByEventIDResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{25}
}

func (x *GetTeamsByEventIDResponse) GetTeams() []*Team {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *GetTeamsByEventIDResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Стартует сразу обе стороны одной игры (game_number), поэтому принимает id
// обеих команд одним вызовом, а не по одной команде за раз.
type StartTeamGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Team1Id       string                 `protobuf:"bytes,1,opt,name=team1_id,json=team1Id,proto3" json:"team1_id,omitempty"`
	Team2Id       string                 `protobuf:"bytes,2,opt,name=team2_id,json=team2Id,proto3" json:"team2_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTeamGameRequest) Reset() {
	*x = StartTeamGameRequest{}
	mi := &file_event_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTeamGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTeamGameRequest) ProtoMessage() {}

func (x *StartTeamGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTeamGameRequest.ProtoReflect.Descriptor instead.
func (*StartTeamGameRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{26}
}

func (x *StartTeamGameRequest) GetTeam1Id() string {
	if x != nil {
		return x.Team1Id
	}
	return ""
}

func (x *StartTeamGameRequest) GetTeam2Id() string {
	if x != nil {
		return x.Team2Id
	}
	return ""
}

type StartTeamGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTeamGameResponse) Reset() {
	*x = StartTeamGameResponse{}
	mi := &file_event_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTeamGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTeamGameResponse) ProtoMessage() {}

func (x *StartTeamGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTeamGameResponse.ProtoReflect.Descriptor instead.
func (*StartTeamGameResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{27}
}

func (x *StartTeamGameResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Закрывает ровно одну игру (game_number) внутри ивента — обе её команды
// сразу, с явным указанием команды-победителя. team_winner_id обязан
// совпадать с team1_id или team2_id, team1_id и team2_id обязаны быть разными.
// Статистику по игрокам эта ручка не трогает — она вносится позже, по одному
// игроку за раз, через AddTeamMemberStats (см. её комментарий). Итог всего
// ивента (winner_side) определяется автоматически, когда закрывается
// последняя из запланированных игр (1, 2 или 3 — см. target_game_count).
type FinishTeamGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Team1Id       string                 `protobuf:"bytes,1,opt,name=team1_id,json=team1Id,proto3" json:"team1_id,omitempty"`
	Team2Id       string                 `protobuf:"bytes,2,opt,name=team2_id,json=team2Id,proto3" json:"team2_id,omitempty"`
	TeamWinnerId  string                 `protobuf:"bytes,3,opt,name=team_winner_id,json=teamWinnerId,proto3" json:"team_winner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishTeamGameRequest) Reset() {
	*x = FinishTeamGameRequest{}
	mi := &file_event_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishTeamGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishTeamGameRequest) ProtoMessage() {}

func (x *FinishTeamGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishTeamGameRequest.ProtoReflect.Descriptor instead.
func (*FinishTeamGameRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{28}
}

func (x *FinishTeamGameRequest) GetTeam1Id() string {
	if x != nil {
		return x.Team1Id
	}
	return ""
}

func (x *FinishTeamGameRequest) GetTeam2Id() string {
	if x != nil {
		return x.Team2Id
	}
	return ""
}

func (x *FinishTeamGameRequest) GetTeamWinnerId() string {
	if x != nil {
		return x.TeamWinnerId
	}
	return ""
}

type FinishTeamGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishTeamGameResponse) Reset() {
	*x = FinishTeamGameResponse{}
	mi := &file_event_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishTeamGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishTeamGameResponse) ProtoMessage() {}

func (x *FinishTeamGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishTeamGameResponse.ProtoReflect.Descriptor instead.
func (*FinishTeamGameResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{29}
}

func (x *FinishTeamGameResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Вызывается один раз на игрока, ПОСЛЕ того как FinishTeamGame уже закрыл
// игру для его команды — заносит статистику этого игрока за прошедшую игру.
// user_id — сырой внешний id (как и везде в API), сервис сам резолвит его в
// user_event_id по паре (user_id, team_id).
type AddTeamMemberStatsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TeamId            string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	UserId            string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Kills             int64                  `protobuf:"varint,3,opt,name=kills,proto3" json:"kills,omitempty"`
	Deaths            int64                  `protobuf:"varint,4,opt,name=deaths,proto3" json:"deaths,omitempty"`
	Points            int64                  `protobuf:"varint,5,opt,name=points,proto3" json:"points,omitempty"`
	Revival           int64                  `protobuf:"varint,6,opt,name=revival,proto3" json:"revival,omitempty"`
	DestroyedVehicles int64                  `protobuf:"varint,7,opt,name=destroyed_vehicles,json=destroyedVehicles,proto3" json:"destroyed_vehicles,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AddTeamMemberStatsRequest) Reset() {
	*x = AddTeamMemberStatsRequest{}
	mi := &file_event_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTeamMemberStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTeamMemberStatsRequest) ProtoMessage() {}

func (x *AddTeamMemberStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTeamMemberStatsRequest.ProtoReflect.Descriptor instead.
func (*AddTeamMemberStatsRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{30}
}

func (x *AddTeamMemberStatsRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *AddTeamMemberStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddTeamMemberStatsRequest) GetKills() int64 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *AddTeamMemberStatsRequest) GetDeaths() int64 {
	if x != nil {
		return x.Deaths
	}
	return 0
}

func (x *AddTeamMemberStatsRequest) GetPoints() int64 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *AddTeamMemberStatsRequest) GetRevival() int64 {
	if x != nil {
		return x.Revival
	}
	return 0
}

func (x *AddTeamMemberStatsRequest) GetDestroyedVehicles() int64 {
	if x != nil {
		return x.DestroyedVehicles
	}
	return 0
}

type AddTeamMemberStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTeamMemberStatsResponse) Reset() {
	*x = AddTeamMemberStatsResponse{}
	mi := &file_event_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTeamMemberStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTeamMemberStatsResponse) ProtoMessage() {}

func (x *AddTeamMemberStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTeamMemberStatsResponse.ProtoReflect.Descriptor instead.
func (*AddTeamMemberStatsResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{31}
}

func (x *AddTeamMemberStatsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetTeamStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamStatsRequest) Reset() {
	*x = GetTeamStatsRequest{}
	mi := &file_event_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamStatsRequest) ProtoMessage() {}

func (x *GetTeamStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamStatsRequest.ProtoReflect.Descriptor instead.
func (*GetTeamStatsRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{32}
}

func (x *GetTeamStatsRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type GetTeamStatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Stats []*TeamMember          `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	// Итог по всей команде — то же, что лежит в Team после FinishTeamGame,
	// отдано отдельными полями, чтобы не заставлять клиента суммировать stats самому.
	TotalKills             int64  `protobuf:"varint,2,opt,name=total_kills,json=totalKills,proto3" json:"total_kills,omitempty"`
	TotalDeaths            int64  `protobuf:"varint,3,opt,name=total_deaths,json=totalDeaths,proto3" json:"total_deaths,omitempty"`
	TotalPoints            int64  `protobuf:"varint,4,opt,name=total_points,json=totalPoints,proto3" json:"total_points,omitempty"`
	TotalRevival           int64  `protobuf:"varint,5,opt,name=total_revival,json=totalRevival,proto3" json:"total_revival,omitempty"`
	TotalDestroyedVehicles int64  `protobuf:"varint,6,opt,name=total_destroyed_vehicles,json=totalDestroyedVehicles,proto3" json:"total_destroyed_vehicles,omitempty"`
	Error                  string `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetTeamStatsResponse) Reset() {
	*x = GetTeamStatsResponse{}
	mi := &file_event_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamStatsResponse) ProtoMessage() {}

func (x *GetTeamStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamStatsResponse.ProtoReflect.Descriptor instead.
func (*GetTeamStatsResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{33}
}

func (x *GetTeamStatsResponse) GetStats() []*TeamMember {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *GetTeamStatsResponse) GetTotalKills() int64 {
	if x != nil {
		return x.TotalKills
	}
	return 0
}

func (x *GetTeamStatsResponse) GetTotalDeaths() int64 {
	if x != nil {
		return x.TotalDeaths
	}
	return 0
}

func (x *GetTeamStatsResponse) GetTotalPoints() int64 {
	if x != nil {
		return x.TotalPoints
	}
	return 0
}

func (x *GetTeamStatsResponse) GetTotalRevival() int64 {
	if x != nil {
		return x.TotalRevival
	}
	return 0
}

func (x *GetTeamStatsResponse) GetTotalDestroyedVehicles() int64 {
	if x != nil {
		return x.TotalDestroyedVehicles
	}
	return 0
}

func (x *GetTeamStatsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetTeamByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamByIDRequest) Reset() {
	*x = GetTeamByIDRequest{}
	mi := &file_event_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamByIDRequest) ProtoMessage() {}

func (x *GetTeamByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamByIDRequest.ProtoReflect.Descriptor instead.
func (*GetTeamByIDRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{34}
}

func (x *GetTeamByIDRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type GetTeamByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Team          *Team                  `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamByIDResponse) Reset() {
	*x = GetTeamByIDResponse{}
	mi := &file_event_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamByIDResponse) ProtoMessage() {}

func (x *GetTeamByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamByIDResponse.ProtoReflect.Descriptor instead.
func (*GetTeamByIDResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{35}
}

func (x *GetTeamByIDResponse) GetTeam() *Team {
	if x != nil {
		return x.Team
	}
	return nil
}

func (x *GetTeamByIDResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type JoinUserToTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinUserToTeamRequest) Reset() {
	*x = JoinUserToTeamRequest{}
	mi := &file_event_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinUserToTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinUserToTeamRequest) ProtoMessage() {}

func (x *JoinUserToTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinUserToTeamRequest.ProtoReflect.Descriptor instead.
func (*JoinUserToTeamRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{36}
}

func (x *JoinUserToTeamRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *JoinUserToTeamRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JoinUserToTeamRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type JoinUserToTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinUserToTeamResponse) Reset() {
	*x = JoinUserToTeamResponse{}
	mi := &file_event_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinUserToTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinUserToTeamResponse) ProtoMessage() {}

func (x *JoinUserToTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinUserToTeamResponse.ProtoReflect.Descriptor instead.
func (*JoinUserToTeamResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{37}
}

func (x *JoinUserToTeamResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RemoveUserFromTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserFromTeamRequest) Reset() {
	*x = RemoveUserFromTeamRequest{}
	mi := &file_event_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserFromTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserFromTeamRequest) ProtoMessage() {}

func (x *RemoveUserFromTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserFromTeamRequest.ProtoReflect.Descriptor instead.
func (*RemoveUserFromTeamRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{38}
}

func (x *RemoveUserFromTeamRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *RemoveUserFromTeamRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RemoveUserFromTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserFromTeamResponse) Reset() {
	*x = RemoveUserFromTeamResponse{}
	mi := &file_event_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserFromTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserFromTeamResponse) ProtoMessage() {}

func (x *RemoveUserFromTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserFromTeamResponse.ProtoReflect.Descriptor instead.
func (*RemoveUserFromTeamResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{39}
}

func (x *RemoveUserFromTeamResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetUnfinishedEventsByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserCreateId  string                 `protobuf:"bytes,1,opt,name=user_create_id,json=userCreateId,proto3" json:"user_create_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnfinishedEventsByUserIDRequest) Reset() {
	*x = GetUnfinishedEventsByUserIDRequest{}
	mi := &file_event_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnfinishedEventsByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnfinishedEventsByUserIDRequest) ProtoMessage() {}

func (x *GetUnfinishedEventsByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnfinishedEventsByUserIDRequest.ProtoReflect.Descriptor instead.
func (*GetUnfinishedEventsByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{40}
}

func (x *GetUnfinishedEventsByUserIDRequest) GetUserCreateId() string {
	if x != nil {
		return x.UserCreateId
	}
	return ""
}

type GetUnfinishedEventsByUserIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnfinishedEventsByUserIDResponse) Reset() {
	*x = GetUnfinishedEventsByUserIDResponse{}
	mi := &file_event_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnfinishedEventsByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnfinishedEventsByUserIDResponse) ProtoMessage() {}

func (x *GetUnfinishedEventsByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnfinishedEventsByUserIDResponse.ProtoReflect.Descriptor instead.
func (*GetUnfinishedEventsByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{41}
}

func (x *GetUnfinishedEventsByUserIDResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetUnfinishedEventsByUserIDResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetUnfinishedEventsByEventNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventName     string                 `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnfinishedEventsByEventNameRequest) Reset() {
	*x = GetUnfinishedEventsByEventNameRequest{}
	mi := &file_event_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnfinishedEventsByEventNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnfinishedEventsByEventNameRequest) ProtoMessage() {}

func (x *GetUnfinishedEventsByEventNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnfinishedEventsByEventNameRequest.ProtoReflect.Descriptor instead.
func (*GetUnfinishedEventsByEventNameRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{42}
}

func (x *GetUnfinishedEventsByEventNameRequest) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

type GetUnfinishedEventsByEventNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnfinishedEventsByEventNameResponse) Reset() {
	*x = GetUnfinishedEventsByEventNameResponse{}
	mi := &file_event_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnfinishedEventsByEventNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnfinishedEventsByEventNameResponse) ProtoMessage() {}

func (x *GetUnfinishedEventsByEventNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnfinishedEventsByEventNameResponse.ProtoReflect.Descriptor instead.
func (*GetUnfinishedEventsByEventNameResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{43}
}

func (x *GetUnfinishedEventsByEventNameResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetUnfinishedEventsByEventNameResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\x05event\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf0\x03\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_name\x18\x02 \x01(\tR\teventName\x12$\n" +
	"\x0euser_create_id\x18\x03 \x01(\tR\fuserCreateId\x12/\n" +
	"\x14enemy_side_leader_id\x18\x04 \x01(\tR\x11enemySideLeaderId\x12\x1d\n" +
	"\n" +
	"user_count\x18\x05 \x01(\x03R\tuserCount\x129\n" +
	"\n" +
	"time_start\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimeStart\x12;\n" +
	"\vtime_finish\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"timeFinish\x12;\n" +
	"\vcreate_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12\x1f\n" +
	"\vwinner_side\x18\t \x01(\tR\n" +
	"winnerSide\x12*\n" +
	"\x11target_game_count\x18\f \x01(\x03R\x0ftargetGameCount\x12\x1d\n" +
	"\n" +
	"game_count\x18\r \x01(\x03R\tgameCount\x12\x16\n" +
	"\x06status\x18\x0e \x01(\tR\x06status\"\xf2\x01\n" +
	"\x04User\x12\"\n" +
	"\ruser_event_id\x18\x01 \x01(\tR\vuserEventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x12\x17\n" +
	"\aclan_id\x18\x04 \x01(\tR\x06clanId\x12\x14\n" +
	"\x05enemy\x18\x05 \x01(\bR\x05enemy\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\x127\n" +
	"\tjoin_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bjoinTimeJ\x04\b\a\x10\bR\x10six_clan_members\"\xfc\x03\n" +
	"\x04Team\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12$\n" +
	"\x0eside_leader_id\x18\x03 \x01(\tR\fsideLeaderId\x12\x1f\n" +
	"\vgame_number\x18\x04 \x01(\x03R\n" +
	"gameNumber\x12#\n" +
	"\rmembers_count\x18\x05 \x01(\x03R\fmembersCount\x12\x16\n" +
	"\x06winner\x18\x06 \x01(\bR\x06winner\x12\x1f\n" +
	"\vtotal_kills\x18\a \x01(\x03R\n" +
	"totalKills\x12!\n" +
	"\ftotal_deaths\x18\b \x01(\x03R\vtotalDeaths\x12!\n" +
	"\ftotal_points\x18\t \x01(\x03R\vtotalPoints\x12#\n" +
	"\rtotal_revival\x18\n" +
	" \x01(\x03R\ftotalRevival\x128\n" +
	"\x18total_destroyed_vehicles\x18\v \x01(\x03R\x16totalDestroyedVehicles\x129\n" +
	"\n" +
	"time_start\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\ttimeStart\x12;\n" +
	"\vtime_finish\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"timeFinish\"\xaf\x02\n" +
	"\n" +
	"TeamMember\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\"\n" +
	"\ruser_event_id\x18\x02 \x01(\tR\vuserEventId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x14\n" +
	"\x05kills\x18\x05 \x01(\x03R\x05kills\x12\x16\n" +
	"\x06deaths\x18\x06 \x01(\x03R\x06deaths\x12\x16\n" +
	"\x06points\x18\a \x01(\x03R\x06points\x12\x18\n" +
	"\arevival\x18\b \x01(\x03R\arevival\x12-\n" +
	"\x12destroyed_vehicles\x18\t \x01(\x03R\x11destroyedVehicles\x12(\n" +
	"\x10six_clan_members\x18\n" +
	" \x01(\bR\x0esixClanMembers\"7\n" +
	"\x1aGetEventMembersListRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"V\n" +
	"\x1bGetEventMembersListResponse\x12!\n" +
	"\x05users\x18\x01 \x03(\v2\v.event.UserR\x05users\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xd5\x02\n" +
	"\x12CreateEventRequest\x12&\n" +
	"\x0fuser_creator_id\x18\x01 \x01(\tR\ruserCreatorId\x12&\n" +
	"\x0fcreator_clan_id\x18\x02 \x01(\tR\rcreatorClanId\x12/\n" +
	"\x14enemy_side_leader_id\x18\x03 \x01(\tR\x11enemySideLeaderId\x128\n" +
	"\x19enemy_side_leader_clan_id\x18\x04 \x01(\tR\x15enemySideLeaderClanId\x12\x1d\n" +
	"\n" +
	"event_name\x18\x05 \x01(\tR\teventName\x129\n" +
	"\n" +
	"time_start\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimeStart\x12*\n" +
	"\x11target_game_count\x18\a \x01(\x03R\x0ftargetGameCount\"+\n" +
	"\x13CreateEventResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"C\n" +
	"\x1bGetEventsByCreatorIdRequest\x12$\n" +
	"\x0euser_create_id\x18\x01 \x01(\tR\fuserCreateId\"Z\n" +
	"\x1cGetEventsByCreatorIdResponse\x12$\n" +
	"\x06events\x18\x01 \x03(\v2\f.event.EventR\x06events\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"F\n" +
	"\x1eGetLastEventByCreatorIdRequest\x12$\n" +
	"\x0euser_create_id\x18\x01 \x01(\tR\fuserCreateId\"[\n" +
	"\x1fGetLastEventByCreatorIdResponse\x12\"\n" +
	"\x05event\x18\x01 \x01(\v2\f.event.EventR\x05event\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"<\n" +
	"\x1bGetEventsByEventNameRequest\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\"Z\n" +
	"\x1cGetEventsByEventNameResponse\x12$\n" +
	"\x06events\x18\x01 \x03(\v2\f.event.EventR\x06events\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x9b\x01\n" +
	"\x16UpdateTimeEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12$\n" +
	"\x0euser_create_id\x18\x02 \x01(\tR\fuserCreateId\x12@\n" +
	"\x0enew_time_start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\fnewTimeStart\"/\n" +
	"\x17UpdateTimeEventResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"U\n" +
	"\x12CancelEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12$\n" +
	"\x0euser_create_id\x18\x02 \x01(\tR\fuserCreateId\"+\n" +
	"\x13CancelEventResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"w\n" +
	"\x12JoinToEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\aclan_id\x18\x03 \x01(\tR\x06clanId\x12\x14\n" +
	"\x05enemy\x18\x04 \x01(\bR\x05enemy\"+\n" +
	"\x13JoinToEventResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"G\n" +
	"\x11LeaveEventRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\"*\n" +
	"\x12LeaveEventResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"~\n" +
	"\x0eSetRoleRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12$\n" +
	"\x0eside_leader_id\x18\x02 \x01(\tR\fsideLeaderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"'\n" +
	"\x0fSetRoleResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"5\n" +
	"\x18GetTeamsByEventIDRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"T\n" +
	"\x19GetTeamsByEventIDResponse\x12!\n" +
	"\x05teams\x18\x01 \x03(\v2\v.event.TeamR\x05teams\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"L\n" +
	"\x14StartTeamGameRequest\x12\x19\n" +
	"\bteam1_id\x18\x01 \x01(\tR\ateam1Id\x12\x19\n" +
	"\bteam2_id\x18\x02 \x01(\tR\ateam2Id\"-\n" +
	"\x15StartTeamGameResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"s\n" +
	"\x15FinishTeamGameRequest\x12\x19\n" +
	"\bteam1_id\x18\x01 \x01(\tR\ateam1Id\x12\x19\n" +
	"\bteam2_id\x18\x02 \x01(\tR\ateam2Id\x12$\n" +
	"\x0eteam_winner_id\x18\x03 \x01(\tR\fteamWinnerId\".\n" +
	"\x16FinishTeamGameResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\xdc\x01\n" +
	"\x19AddTeamMemberStatsRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05kills\x18\x03 \x01(\x03R\x05kills\x12\x16\n" +
	"\x06deaths\x18\x04 \x01(\x03R\x06deaths\x12\x16\n" +
	"\x06points\x18\x05 \x01(\x03R\x06points\x12\x18\n" +
	"\arevival\x18\x06 \x01(\x03R\arevival\x12-\n" +
	"\x12destroyed_vehicles\x18\a \x01(\x03R\x11destroyedVehicles\"2\n" +
	"\x1aAddTeamMemberStatsResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\".\n" +
	"\x13GetTeamStatsRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\"\x9b\x02\n" +
	"\x14GetTeamStatsResponse\x12'\n" +
	"\x05stats\x18\x01 \x03(\v2\x11.event.TeamMemberR\x05stats\x12\x1f\n" +
	"\vtotal_kills\x18\x02 \x01(\x03R\n" +
	"totalKills\x12!\n" +
	"\ftotal_deaths\x18\x03 \x01(\x03R\vtotalDeaths\x12!\n" +
	"\ftotal_points\x18\x04 \x01(\x03R\vtotalPoints\x12#\n" +
	"\rtotal_revival\x18\x05 \x01(\x03R\ftotalRevival\x128\n" +
	"\x18total_destroyed_vehicles\x18\x06 \x01(\x03R\x16totalDestroyedVehicles\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"-\n" +
	"\x12GetTeamByIDRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\"L\n" +
	"\x13GetTeamByIDResponse\x12\x1f\n" +
	"\x04team\x18\x01 \x01(\v2\v.event.TeamR\x04team\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"]\n" +
	"\x15JoinUserToTeamRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\".\n" +
	"\x16JoinUserToTeamResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"M\n" +
	"\x19RemoveUserFromTeamRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"2\n" +
	"\x1aRemoveUserFromTeamResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"J\n" +
	"\"GetUnfinishedEventsByUserIDRequest\x12$\n" +
	"\x0euser_create_id\x18\x01 \x01(\tR\fuserCreateId\"a\n" +
	"#GetUnfinishedEventsByUserIDResponse\x12$\n" +
	"\x06events\x18\x01 \x03(\v2\f.event.EventR\x06events\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"F\n" +
	"%GetUnfinishedEventsByEventNameRequest\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\"d\n" +
	"&GetUnfinishedEventsByEventNameResponse\x12$\n" +
	"\x06events\x18\x01 \x03(\v2\f.event.EventR\x06events\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xb5\r\n" +
	"\fEventService\x12D\n" +
	"\vCreateEvent\x12\x19.event.CreateEventRequest\x1a\x1a.event.CreateEventResponse\x12_\n" +
	"\x14GetEventsByCreatorId\x12\".event.GetEventsByCreatorIdRequest\x1a#.event.GetEventsByCreatorIdResponse\x12h\n" +
	"\x17GetLastEventByCreatorId\x12%.event.GetLastEventByCreatorIdRequest\x1a&.event.GetLastEventByCreatorIdResponse\x12_\n" +
	"\x14GetEventsByEventName\x12\".event.GetEventsByEventNameRequest\x1a#.event.GetEventsByEventNameResponse\x12t\n" +
	"\x1bGetUnfinishedEventsByUserID\x12).event.GetUnfinishedEventsByUserIDRequest\x1a*.event.GetUnfinishedEventsByUserIDResponse\x12}\n" +
	"\x1eGetUnfinishedEventsByEventName\x12,.event.GetUnfinishedEventsByEventNameRequest\x1a-.event.GetUnfinishedEventsByEventNameResponse\x12P\n" +
	"\x0fUpdateTimeEvent\x12\x1d.event.UpdateTimeEventRequest\x1a\x1e.event.UpdateTimeEventResponse\x12D\n" +
	"\vCancelEvent\x12\x19.event.CancelEventRequest\x1a\x1a.event.CancelEventResponse\x12D\n" +
	"\vJoinToEvent\x12\x19.event.JoinToEventRequest\x1a\x1a.event.JoinToEventResponse\x12A\n" +
	"\n" +
	"LeaveEvent\x12\x18.event.LeaveEventRequest\x1a\x19.event.LeaveEventResponse\x128\n" +
	"\aSetRole\x12\x15.event.SetRoleRequest\x1a\x16.event.SetRoleResponse\x12\\\n" +
	"\x13GetEventMembersList\x12!.event.GetEventMembersListRequest\x1a\".event.GetEventMembersListResponse\x12V\n" +
	"\x11GetTeamsByEventID\x12\x1f.event.GetTeamsByEventIDRequest\x1a .event.GetTeamsByEventIDResponse\x12J\n" +
	"\rStartTeamGame\x12\x1b.event.StartTeamGameRequest\x1a\x1c.event.StartTeamGameResponse\x12M\n" +
	"\x0eFinishTeamGame\x12\x1c.event.FinishTeamGameRequest\x1a\x1d.event.FinishTeamGameResponse\x12Y\n" +
	"\x12AddTeamMemberStats\x12 .event.AddTeamMemberStatsRequest\x1a!.event.AddTeamMemberStatsResponse\x12G\n" +
	"\fGetTeamStats\x12\x1a.event.GetTeamStatsRequest\x1a\x1b.event.GetTeamStatsResponse\x12D\n" +
	"\vGetTeamByID\x12\x19.event.GetTeamByIDRequest\x1a\x1a.event.GetTeamByIDResponse\x12M\n" +
	"\x0eJoinUserToTeam\x12\x1c.event.JoinUserToTeamRequest\x1a\x1d.event.JoinUserToTeamResponse\x12Y\n" +
	"\x12RemoveUserFromTeam\x12 .event.RemoveUserFromTeamRequest\x1a!.event.RemoveUserFromTeamResponseB#Z!event-service/internal/core/protob\x06proto3"

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData []byte
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)))
	})
	return file_event_proto_rawDescData
}

var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 44)
var file_event_proto_goTypes = []any{
	(*Event)(nil),                                  // 0: event.Event
	(*User)(nil),                                   // 1: event.User
	(*Team)(nil),                                   // 2: event.Team
	(*TeamMember)(nil),                             // 3: event.TeamMember
	(*GetEventMembersListRequest)(nil),             // 4: event.GetEventMembersListRequest
	(*GetEventMembersListResponse)(nil),            // 5: event.GetEventMembersListResponse
	(*CreateEventRequest)(nil),                     // 6: event.CreateEventRequest
	(*CreateEventResponse)(nil),                    // 7: event.CreateEventResponse
	(*GetEventsByCreatorIdRequest)(nil),            // 8: event.GetEventsByCreatorIdRequest
	(*GetEventsByCreatorIdResponse)(nil),           // 9: event.GetEventsByCreatorIdResponse
	(*GetLastEventByCreatorIdRequest)(nil),         // 10: event.GetLastEventByCreatorIdRequest
	(*GetLastEventByCreatorIdResponse)(nil),        // 11: event.GetLastEventByCreatorIdResponse
	(*GetEventsByEventNameRequest)(nil),            // 12: event.GetEventsByEventNameRequest
	(*GetEventsByEventNameResponse)(nil),           // 13: event.GetEventsByEventNameResponse
	(*UpdateTimeEventRequest)(nil),                 // 14: event.UpdateTimeEventRequest
	(*UpdateTimeEventResponse)(nil),                // 15: event.UpdateTimeEventResponse
	(*CancelEventRequest)(nil),                     // 16: event.CancelEventRequest
	(*CancelEventResponse)(nil),                    // 17: event.CancelEventResponse
	(*JoinToEventRequest)(nil),                     // 18: event.JoinToEventRequest
	(*JoinToEventResponse)(nil),                    // 19: event.JoinToEventResponse
	(*LeaveEventRequest)(nil),                      // 20: event.LeaveEventRequest
	(*LeaveEventResponse)(nil),                     // 21: event.LeaveEventResponse
	(*SetRoleRequest)(nil),                         // 22: event.SetRoleRequest
	(*SetRoleResponse)(nil),                        // 23: event.SetRoleResponse
	(*GetTeamsByEventIDRequest)(nil),               // 24: event.GetTeamsByEventIDRequest
	(*GetTeamsByEventIDResponse)(nil),              // 25: event.GetTeamsByEventIDResponse
	(*StartTeamGameRequest)(nil),                   // 26: event.StartTeamGameRequest
	(*StartTeamGameResponse)(nil),                  // 27: event.StartTeamGameResponse
	(*FinishTeamGameRequest)(nil),                  // 28: event.FinishTeamGameRequest
	(*FinishTeamGameResponse)(nil),                 // 29: event.FinishTeamGameResponse
	(*AddTeamMemberStatsRequest)(nil),              // 30: event.AddTeamMemberStatsRequest
	(*AddTeamMemberStatsResponse)(nil),             // 31: event.AddTeamMemberStatsResponse
	(*GetTeamStatsRequest)(nil),                    // 32: event.GetTeamStatsRequest
	(*GetTeamStatsResponse)(nil),                   // 33: event.GetTeamStatsResponse
	(*GetTeamByIDRequest)(nil),                     // 34: event.GetTeamByIDRequest
	(*GetTeamByIDResponse)(nil),                    // 35: event.GetTeamByIDResponse
	(*JoinUserToTeamRequest)(nil),                  // 36: event.JoinUserToTeamRequest
	(*JoinUserToTeamResponse)(nil),                 // 37: event.JoinUserToTeamResponse
	(*RemoveUserFromTeamRequest)(nil),              // 38: event.RemoveUserFromTeamRequest
	(*RemoveUserFromTeamResponse)(nil),             // 39: event.RemoveUserFromTeamResponse
	(*GetUnfinishedEventsByUserIDRequest)(nil),     // 40: event.GetUnfinishedEventsByUserIDRequest
	(*GetUnfinishedEventsByUserIDResponse)(nil),    // 41: event.GetUnfinishedEventsByUserIDResponse
	(*GetUnfinishedEventsByEventNameRequest)(nil),  // 42: event.GetUnfinishedEventsByEventNameRequest
	(*GetUnfinishedEventsByEventNameResponse)(nil), // 43: event.GetUnfinishedEventsByEventNameResponse
	(*timestamppb.Timestamp)(nil),                  // 44: google.protobuf.Timestamp
}
var file_event_proto_depIdxs = []int32{
	44, // 0: event.Event.time_start:type_name -> google.protobuf.Timestamp
	44, // 1: event.Event.time_finish:type_name -> google.protobuf.Timestamp
	44, // 2: event.Event.create_time:type_name -> google.protobuf.Timestamp
	44, // 3: event.User.join_time:type_name -> google.protobuf.Timestamp
	44, // 4: event.Team.time_start:type_name -> google.protobuf.Timestamp
	44, // 5: event.Team.time_finish:type_name -> google.protobuf.Timestamp
	1,  // 6: event.GetEventMembersListResponse.users:type_name -> event.User
	44, // 7: event.CreateEventRequest.time_start:type_name -> google.protobuf.Timestamp
	0,  // 8: event.GetEventsByCreatorIdResponse.events:type_name -> event.Event
	0,  // 9: event.GetLastEventByCreatorIdResponse.event:type_name -> event.Event
	0,  // 10: event.GetEventsByEventNameResponse.events:type_name -> event.Event
	44, // 11: event.UpdateTimeEventRequest.new_time_start:type_name -> google.protobuf.Timestamp
	2,  // 12: event.GetTeamsByEventIDResponse.teams:type_name -> event.Team
	3,  // 13: event.GetTeamStatsResponse.stats:type_name -> event.TeamMember
	2,  // 14: event.GetTeamByIDResponse.team:type_name -> event.Team
	0,  // 15: event.GetUnfinishedEventsByUserIDResponse.events:type_name -> event.Event
	0,  // 16: event.GetUnfinishedEventsByEventNameResponse.events:type_name -> event.Event
	6,  // 17: event.EventService.CreateEvent:input_type -> event.CreateEventRequest
	8,  // 18: event.EventService.GetEventsByCreatorId:input_type -> event.GetEventsByCreatorIdRequest
	10, // 19: event.EventService.GetLastEventByCreatorId:input_type -> event.GetLastEventByCreatorIdRequest
	12, // 20: event.EventService.GetEventsByEventName:input_type -> event.GetEventsByEventNameRequest
	40, // 21: event.EventService.GetUnfinishedEventsByUserID:input_type -> event.GetUnfinishedEventsByUserIDRequest
	42, // 22: event.EventService.GetUnfinishedEventsByEventName:input_type -> event.GetUnfinishedEventsByEventNameRequest
	14, // 23: event.EventService.UpdateTimeEvent:input_type -> event.UpdateTimeEventRequest
	16, // 24: event.EventService.CancelEvent:input_type -> event.CancelEventRequest
	18, // 25: event.EventService.JoinToEvent:input_type -> event.JoinToEventRequest
	20, // 26: event.EventService.LeaveEvent:input_type -> event.LeaveEventRequest
	22, // 27: event.EventService.SetRole:input_type -> event.SetRoleRequest
	4,  // 28: event.EventService.GetEventMembersList:input_type -> event.GetEventMembersListRequest
	24, // 29: event.EventService.GetTeamsByEventID:input_type -> event.GetTeamsByEventIDRequest
	26, // 30: event.EventService.StartTeamGame:input_type -> event.StartTeamGameRequest
	28, // 31: event.EventService.FinishTeamGame:input_type -> event.FinishTeamGameRequest
	30, // 32: event.EventService.AddTeamMemberStats:input_type -> event.AddTeamMemberStatsRequest
	32, // 33: event.EventService.GetTeamStats:input_type -> event.GetTeamStatsRequest
	34, // 34: event.EventService.GetTeamByID:input_type -> event.GetTeamByIDRequest
	36, // 35: event.EventService.JoinUserToTeam:input_type -> event.JoinUserToTeamRequest
	38, // 36: event.EventService.RemoveUserFromTeam:input_type -> event.RemoveUserFromTeamRequest
	7,  // 37: event.EventService.CreateEvent:output_type -> event.CreateEventResponse
	9,  // 38: event.EventService.GetEventsByCreatorId:output_type -> event.GetEventsByCreatorIdResponse
	11, // 39: event.EventService.GetLastEventByCreatorId:output_type -> event.GetLastEventByCreatorIdResponse
	13, // 40: event.EventService.GetEventsByEventName:output_type -> event.GetEventsByEventNameResponse
	41, // 41: event.EventService.GetUnfinishedEventsByUserID:output_type -> event.GetUnfinishedEventsByUserIDResponse
	43, // 42: event.EventService.GetUnfinishedEventsByEventName:output_type -> event.GetUnfinishedEventsByEventNameResponse
	15, // 43: event.EventService.UpdateTimeEvent:output_type -> event.UpdateTimeEventResponse
	17, // 44: event.EventService.CancelEvent:output_type -> event.CancelEventResponse
	19, // 45: event.EventService.JoinToEvent:output_type -> event.JoinToEventResponse
	21, // 46: event.EventService.LeaveEvent:output_type -> event.LeaveEventResponse
	23, // 47: event.EventService.SetRole:output_type -> event.SetRoleResponse
	5,  // 48: event.EventService.GetEventMembersList:output_type -> event.GetEventMembersListResponse
	25, // 49: event.EventService.GetTeamsByEventID:output_type -> event.GetTeamsByEventIDResponse
	27, // 50: event.EventService.StartTeamGame:output_type -> event.StartTeamGameResponse
	29, // 51: event.EventService.FinishTeamGame:output_type -> event.FinishTeamGameResponse
	31, // 52: event.EventService.AddTeamMemberStats:output_type -> event.AddTeamMemberStatsResponse
	33, // 53: event.EventService.GetTeamStats:output_type -> event.GetTeamStatsResponse
	35, // 54: event.EventService.GetTeamByID:output_type -> event.GetTeamByIDResponse
	37, // 55: event.EventService.JoinUserToTeam:output_type -> event.JoinUserToTeamResponse
	39, // 56: event.EventService.RemoveUserFromTeam:output_type -> event.RemoveUserFromTeamResponse
	37, // [37:57] is the sub-list for method output_type
	17, // [17:37] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   44,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
