// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: event.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventService_CreateEvent_FullMethodName                    = "/event.EventService/CreateEvent"
	EventService_GetEventsByCreatorId_FullMethodName           = "/event.EventService/GetEventsByCreatorId"
	EventService_GetLastEventByCreatorId_FullMethodName        = "/event.EventService/GetLastEventByCreatorId"
	EventService_GetEventsByEventName_FullMethodName           = "/event.EventService/GetEventsByEventName"
	EventService_GetUnfinishedEventsByUserID_FullMethodName    = "/event.EventService/GetUnfinishedEventsByUserID"
	EventService_GetUnfinishedEventsByEventName_FullMethodName = "/event.EventService/GetUnfinishedEventsByEventName"
	EventService_UpdateTimeEvent_FullMethodName                = "/event.EventService/UpdateTimeEvent"
	EventService_DeleteEvent_FullMethodName                    = "/event.EventService/DeleteEvent"
	EventService_JoinToEvent_FullMethodName                    = "/event.EventService/JoinToEvent"
	EventService_LeaveEvent_FullMethodName                     = "/event.EventService/LeaveEvent"
	EventService_SetRole_FullMethodName                        = "/event.EventService/SetRole"
	EventService_GetEventMembersList_FullMethodName            = "/event.EventService/GetEventMembersList"
	EventService_GetTeamsByEventID_FullMethodName              = "/event.EventService/GetTeamsByEventID"
	EventService_StartTeamGame_FullMethodName                  = "/event.EventService/StartTeamGame"
	EventService_FinishTeamGame_FullMethodName                 = "/event.EventService/FinishTeamGame"
	EventService_AddTeamMemberStats_FullMethodName             = "/event.EventService/AddTeamMemberStats"
	EventService_GetTeamStats_FullMethodName                   = "/event.EventService/GetTeamStats"
	EventService_GetTeamByID_FullMethodName                    = "/event.EventService/GetTeamByID"
	EventService_AddUserToTeam_FullMethodName                  = "/event.EventService/AddUserToTeam"
	EventService_RemoveUserFromTeam_FullMethodName             = "/event.EventService/RemoveUserFromTeam"
)

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventServiceClient interface {
	CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*CreateEventResponse, error)
	GetEventsByCreatorId(ctx context.Context, in *GetEventsByCreatorIdRequest, opts ...grpc.CallOption) (*GetEventsByCreatorIdResponse, error)
	GetLastEventByCreatorId(ctx context.Context, in *GetLastEventByCreatorIdRequest, opts ...grpc.CallOption) (*GetLastEventByCreatorIdResponse, error)
	GetEventsByEventName(ctx context.Context, in *GetEventsByEventNameRequest, opts ...grpc.CallOption) (*GetEventsByEventNameResponse, error)
	GetUnfinishedEventsByUserID(ctx context.Context, in *GetUnfinishedEventsByUserIDRequest, opts ...grpc.CallOption) (*GetUnfinishedEventsByUserIDResponse, error)
	GetUnfinishedEventsByEventName(ctx context.Context, in *GetUnfinishedEventsByEventNameRequest, opts ...grpc.CallOption) (*GetUnfinishedEventsByEventNameResponse, error)
	UpdateTimeEvent(ctx context.Context, in *UpdateTimeEventRequest, opts ...grpc.CallOption) (*UpdateTimeEventResponse, error)
	DeleteEvent(ctx context.Context, in *DeleteEventRequest, opts ...grpc.CallOption) (*DeleteEventResponse, error)
	JoinToEvent(ctx context.Context, in *JoinToEventRequest, opts ...grpc.CallOption) (*JoinToEventResponse, error)
	LeaveEvent(ctx context.Context, in *LeaveEventRequest, opts ...grpc.CallOption) (*LeaveEventResponse, error)
	SetRole(ctx context.Context, in *SetRoleRequest, opts ...grpc.CallOption) (*SetRoleResponse, error)
	GetEventMembersList(ctx context.Context, in *GetEventMembersListRequest, opts ...grpc.CallOption) (*GetEventMembersListResponse, error)
	GetTeamsByEventID(ctx context.Context, in *GetTeamsByEventIDRequest, opts ...grpc.CallOption) (*GetTeamsByEventIDResponse, error)
	StartTeamGame(ctx context.Context, in *StartTeamGameRequest, opts ...grpc.CallOption) (*StartTeamGameResponse, error)
	FinishTeamGame(ctx context.Context, in *FinishTeamGameRequest, opts ...grpc.CallOption) (*FinishTeamGameResponse, error)
	AddTeamMemberStats(ctx context.Context, in *AddTeamMemberStatsRequest, opts ...grpc.CallOption) (*AddTeamMemberStatsResponse, error)
	GetTeamStats(ctx context.Context, in *GetTeamStatsRequest, opts ...grpc.CallOption) (*GetTeamStatsResponse, error)
	GetTeamByID(ctx context.Context, in *GetTeamByIDRequest, opts ...grpc.CallOption) (*GetTeamByIDResponse, error)
	AddUserToTeam(ctx context.Context, in *AddUserToTeamRequest, opts ...grpc.CallOption) (*AddUserToTeamResponse, error)
	RemoveUserFromTeam(ctx context.Context, in *RemoveUserFromTeamRequest, opts ...grpc.CallOption) (*RemoveUserFromTeamResponse, error)
}

type eventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventServiceClient(cc grpc.ClientConnInterface) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*CreateEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEventResponse)
	err := c.cc.Invoke(ctx, EventService_CreateEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetEventsByCreatorId(ctx context.Context, in *GetEventsByCreatorIdRequest, opts ...grpc.CallOption) (*GetEventsByCreatorIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventsByCreatorIdResponse)
	err := c.cc.Invoke(ctx, EventService_GetEventsByCreatorId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetLastEventByCreatorId(ctx context.Context, in *GetLastEventByCreatorIdRequest, opts ...grpc.CallOption) (*GetLastEventByCreatorIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLastEventByCreatorIdResponse)
	err := c.cc.Invoke(ctx, EventService_GetLastEventByCreatorId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetEventsByEventName(ctx context.Context, in *GetEventsByEventNameRequest, opts ...grpc.CallOption) (*GetEventsByEventNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventsByEventNameResponse)
	err := c.cc.Invoke(ctx, EventService_GetEventsByEventName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetUnfinishedEventsByUserID(ctx context.Context, in *GetUnfinishedEventsByUserIDRequest, opts ...grpc.CallOption) (*GetUnfinishedEventsByUserIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUnfinishedEventsByUserIDResponse)
	err := c.cc.Invoke(ctx, EventService_GetUnfinishedEventsByUserID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetUnfinishedEventsByEventName(ctx context.Context, in *GetUnfinishedEventsByEventNameRequest, opts ...grpc.CallOption) (*GetUnfinishedEventsByEventNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUnfinishedEventsByEventNameResponse)
	err := c.cc.Invoke(ctx, EventService_GetUnfinishedEventsByEventName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) UpdateTimeEvent(ctx context.Context, in *UpdateTimeEventRequest, opts ...grpc.CallOption) (*UpdateTimeEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTimeEventResponse)
	err := c.cc.Invoke(ctx, EventService_UpdateTimeEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) DeleteEvent(ctx context.Context, in *DeleteEventRequest, opts ...grpc.CallOption) (*DeleteEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEventResponse)
	err := c.cc.Invoke(ctx, EventService_DeleteEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) JoinToEvent(ctx context.Context, in *JoinToEventRequest, opts ...grpc.CallOption) (*JoinToEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinToEventResponse)
	err := c.cc.Invoke(ctx, EventService_JoinToEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) LeaveEvent(ctx context.Context, in *LeaveEventRequest, opts ...grpc.CallOption) (*LeaveEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveEventResponse)
	err := c.cc.Invoke(ctx, EventService_LeaveEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) SetRole(ctx context.Context, in *SetRoleRequest, opts ...grpc.CallOption) (*SetRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetRoleResponse)
	err := c.cc.Invoke(ctx, EventService_SetRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetEventMembersList(ctx context.Context, in *GetEventMembersListRequest, opts ...grpc.CallOption) (*GetEventMembersListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventMembersListResponse)
	err := c.cc.Invoke(ctx, EventService_GetEventMembersList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetTeamsByEventID(ctx context.Context, in *GetTeamsByEventIDRequest, opts ...grpc.CallOption) (*GetTeamsByEventIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTeamsByEventIDResponse)
	err := c.cc.Invoke(ctx, EventService_GetTeamsByEventID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) StartTeamGame(ctx context.Context, in *StartTeamGameRequest, opts ...grpc.CallOption) (*StartTeamGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartTeamGameResponse)
	err := c.cc.Invoke(ctx, EventService_StartTeamGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) FinishTeamGame(ctx context.Context, in *FinishTeamGameRequest, opts ...grpc.CallOption) (*FinishTeamGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinishTeamGameResponse)
	err := c.cc.Invoke(ctx, EventService_FinishTeamGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) AddTeamMemberStats(ctx context.Context, in *AddTeamMemberStatsRequest, opts ...grpc.CallOption) (*AddTeamMemberStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddTeamMemberStatsResponse)
	err := c.cc.Invoke(ctx, EventService_AddTeamMemberStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetTeamStats(ctx context.Context, in *GetTeamStatsRequest, opts ...grpc.CallOption) (*GetTeamStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTeamStatsResponse)
	err := c.cc.Invoke(ctx, EventService_GetTeamStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetTeamByID(ctx context.Context, in *GetTeamByIDRequest, opts ...grpc.CallOption) (*GetTeamByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTeamByIDResponse)
	err := c.cc.Invoke(ctx, EventService_GetTeamByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) AddUserToTeam(ctx context.Context, in *AddUserToTeamRequest, opts ...grpc.CallOption) (*AddUserToTeamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddUserToTeamResponse)
	err := c.cc.Invoke(ctx, EventService_AddUserToTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) RemoveUserFromTeam(ctx context.Context, in *RemoveUserFromTeamRequest, opts ...grpc.CallOption) (*RemoveUserFromTeamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveUserFromTeamResponse)
	err := c.cc.Invoke(ctx, EventService_RemoveUserFromTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServiceServer is the server API for EventService service.
// All implementations must embed UnimplementedEventServiceServer
// for forward compatibility.
type EventServiceServer interface {
	CreateEvent(context.Context, *CreateEventRequest) (*CreateEventResponse, error)
	GetEventsByCreatorId(context.Context, *GetEventsByCreatorIdRequest) (*GetEventsByCreatorIdResponse, error)
	GetLastEventByCreatorId(context.Context, *GetLastEventByCreatorIdRequest) (*GetLastEventByCreatorIdResponse, error)
	GetEventsByEventName(context.Context, *GetEventsByEventNameRequest) (*GetEventsByEventNameResponse, error)
	GetUnfinishedEventsByUserID(context.Context, *GetUnfinishedEventsByUserIDRequest) (*GetUnfinishedEventsByUserIDResponse, error)
	GetUnfinishedEventsByEventName(context.Context, *GetUnfinishedEventsByEventNameRequest) (*GetUnfinishedEventsByEventNameResponse, error)
	UpdateTimeEvent(context.Context, *UpdateTimeEventRequest) (*UpdateTimeEventResponse, error)
	DeleteEvent(context.Context, *DeleteEventRequest) (*DeleteEventResponse, error)
	JoinToEvent(context.Context, *JoinToEventRequest) (*JoinToEventResponse, error)
	LeaveEvent(context.Context, *LeaveEventRequest) (*LeaveEventResponse, error)
	SetRole(context.Context, *SetRoleRequest) (*SetRoleResponse, error)
	GetEventMembersList(context.Context, *GetEventMembersListRequest) (*GetEventMembersListResponse, error)
	GetTeamsByEventID(context.Context, *GetTeamsByEventIDRequest) (*GetTeamsByEventIDResponse, error)
	StartTeamGame(context.Context, *StartTeamGameRequest) (*StartTeamGameResponse, error)
	FinishTeamGame(context.Context, *FinishTeamGameRequest) (*FinishTeamGameResponse, error)
	AddTeamMemberStats(context.Context, *AddTeamMemberStatsRequest) (*AddTeamMemberStatsResponse, error)
	GetTeamStats(context.Context, *GetTeamStatsRequest) (*GetTeamStatsResponse, error)
	GetTeamByID(context.Context, *GetTeamByIDRequest) (*GetTeamByIDResponse, error)
	AddUserToTeam(context.Context, *AddUserToTeamRequest) (*AddUserToTeamResponse, error)
	RemoveUserFromTeam(context.Context, *RemoveUserFromTeamRequest) (*RemoveUserFromTeamResponse, error)
	mustEmbedUnimplementedEventServiceServer()
}

// UnimplementedEventServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventServiceServer struct{}

func (UnimplementedEventServiceServer) CreateEvent(context.Context, *CreateEventRequest) (*CreateEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEvent not implemented")
}
func (UnimplementedEventServiceServer) GetEventsByCreatorId(context.Context, *GetEventsByCreatorIdRequest) (*GetEventsByCreatorIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventsByCreatorId not implemented")
}
func (UnimplementedEventServiceServer) GetLastEventByCreatorId(context.Context, *GetLastEventByCreatorIdRequest) (*GetLastEventByCreatorIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLastEventByCreatorId not implemented")
}
func (UnimplementedEventServiceServer) GetEventsByEventName(context.Context, *GetEventsByEventNameRequest) (*GetEventsByEventNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventsByEventName not implemented")
}
func (UnimplementedEventServiceServer) GetUnfinishedEventsByUserID(context.Context, *GetUnfinishedEventsByUserIDRequest) (*GetUnfinishedEventsByUserIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUnfinishedEventsByUserID not implemented")
}
func (UnimplementedEventServiceServer) GetUnfinishedEventsByEventName(context.Context, *GetUnfinishedEventsByEventNameRequest) (*GetUnfinishedEventsByEventNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUnfinishedEventsByEventName not implemented")
}
func (UnimplementedEventServiceServer) UpdateTimeEvent(context.Context, *UpdateTimeEventRequest) (*UpdateTimeEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTimeEvent not implemented")
}
func (UnimplementedEventServiceServer) DeleteEvent(context.Context, *DeleteEventRequest) (*DeleteEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEvent not implemented")
}
func (UnimplementedEventServiceServer) JoinToEvent(context.Context, *JoinToEventRequest) (*JoinToEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinToEvent not implemented")
}
func (UnimplementedEventServiceServer) LeaveEvent(context.Context, *LeaveEventRequest) (*LeaveEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaveEvent not implemented")
}
func (UnimplementedEventServiceServer) SetRole(context.Context, *SetRoleRequest) (*SetRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetRole not implemented")
}
func (UnimplementedEventServiceServer) GetEventMembersList(context.Context, *GetEventMembersListRequest) (*GetEventMembersListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventMembersList not implemented")
}
func (UnimplementedEventServiceServer) GetTeamsByEventID(context.Context, *GetTeamsByEventIDRequest) (*GetTeamsByEventIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTeamsByEventID not implemented")
}
func (UnimplementedEventServiceServer) StartTeamGame(context.Context, *StartTeamGameRequest) (*StartTeamGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartTeamGame not implemented")
}
func (UnimplementedEventServiceServer) FinishTeamGame(context.Context, *FinishTeamGameRequest) (*FinishTeamGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FinishTeamGame not implemented")
}
func (UnimplementedEventServiceServer) AddTeamMemberStats(context.Context, *AddTeamMemberStatsRequest) (*AddTeamMemberStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTeamMemberStats not implemented")
}
func (UnimplementedEventServiceServer) GetTeamStats(context.Context, *GetTeamStatsRequest) (*GetTeamStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTeamStats not implemented")
}
func (UnimplementedEventServiceServer) GetTeamByID(context.Context, *GetTeamByIDRequest) (*GetTeamByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTeamByID not implemented")
}
func (UnimplementedEventServiceServer) AddUserToTeam(context.Context, *AddUserToTeamRequest) (*AddUserToTeamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddUserToTeam not implemented")
}
func (UnimplementedEventServiceServer) RemoveUserFromTeam(context.Context, *RemoveUserFromTeamRequest) (*RemoveUserFromTeamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveUserFromTeam not implemented")
}
func (UnimplementedEventServiceServer) mustEmbedUnimplementedEventServiceServer() {}
func (UnimplementedEventServiceServer) testEmbeddedByValue()                      {}

// UnsafeEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventServiceServer will
// result in compilation errors.
type UnsafeEventServiceServer interface {
	mustEmbedUnimplementedEventServiceServer()
}

func RegisterEventServiceServer(s grpc.ServiceRegistrar, srv EventServiceServer) {
	// If the following call panics, it indicates UnimplementedEventServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventService_ServiceDesc, srv)
}

func _EventService_CreateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).CreateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_CreateEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).CreateEvent(ctx, req.(*CreateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetEventsByCreatorId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsByCreatorIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetEventsByCreatorId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetEventsByCreatorId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetEventsByCreatorId(ctx, req.(*GetEventsByCreatorIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetLastEventByCreatorId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLastEventByCreatorIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetLastEventByCreatorId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetLastEventByCreatorId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetLastEventByCreatorId(ctx, req.(*GetLastEventByCreatorIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetEventsByEventName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsByEventNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetEventsByEventName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetEventsByEventName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetEventsByEventName(ctx, req.(*GetEventsByEventNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetUnfinishedEventsByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnfinishedEventsByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetUnfinishedEventsByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetUnfinishedEventsByUserID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetUnfinishedEventsByUserID(ctx, req.(*GetUnfinishedEventsByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetUnfinishedEventsByEventName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnfinishedEventsByEventNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetUnfinishedEventsByEventName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetUnfinishedEventsByEventName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetUnfinishedEventsByEventName(ctx, req.(*GetUnfinishedEventsByEventNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_UpdateTimeEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTimeEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).UpdateTimeEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_UpdateTimeEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).UpdateTimeEvent(ctx, req.(*UpdateTimeEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_DeleteEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).DeleteEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_DeleteEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).DeleteEvent(ctx, req.(*DeleteEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_JoinToEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinToEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).JoinToEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_JoinToEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).JoinToEvent(ctx, req.(*JoinToEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_LeaveEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).LeaveEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_LeaveEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).LeaveEvent(ctx, req.(*LeaveEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_SetRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).SetRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_SetRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).SetRole(ctx, req.(*SetRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetEventMembersList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventMembersListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetEventMembersList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetEventMembersList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetEventMembersList(ctx, req.(*GetEventMembersListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetTeamsByEventID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeamsByEventIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetTeamsByEventID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetTeamsByEventID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetTeamsByEventID(ctx, req.(*GetTeamsByEventIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_StartTeamGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTeamGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).StartTeamGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_StartTeamGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).StartTeamGame(ctx, req.(*StartTeamGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_FinishTeamGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishTeamGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).FinishTeamGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_FinishTeamGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).FinishTeamGame(ctx, req.(*FinishTeamGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_AddTeamMemberStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTeamMemberStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).AddTeamMemberStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_AddTeamMemberStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).AddTeamMemberStats(ctx, req.(*AddTeamMemberStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetTeamStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeamStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetTeamStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetTeamStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetTeamStats(ctx, req.(*GetTeamStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetTeamByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeamByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetTeamByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetTeamByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetTeamByID(ctx, req.(*GetTeamByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_AddUserToTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserToTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).AddUserToTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_AddUserToTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).AddUserToTeam(ctx, req.(*AddUserToTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_RemoveUserFromTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveUserFromTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).RemoveUserFromTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_RemoveUserFromTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).RemoveUserFromTeam(ctx, req.(*RemoveUserFromTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventService_ServiceDesc is the grpc.ServiceDesc for EventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "event.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEvent",
			Handler:    _EventService_CreateEvent_Handler,
		},
		{
			MethodName: "GetEventsByCreatorId",
			Handler:    _EventService_GetEventsByCreatorId_Handler,
		},
		{
			MethodName: "GetLastEventByCreatorId",
			Handler:    _EventService_GetLastEventByCreatorId_Handler,
		},
		{
			MethodName: "GetEventsByEventName",
			Handler:    _EventService_GetEventsByEventName_Handler,
		},
		{
			MethodName: "GetUnfinishedEventsByUserID",
			Handler:    _EventService_GetUnfinishedEventsByUserID_Handler,
		},
		{
			MethodName: "GetUnfinishedEventsByEventName",
			Handler:    _EventService_GetUnfinishedEventsByEventName_Handler,
		},
		{
			MethodName: "UpdateTimeEvent",
			Handler:    _EventService_UpdateTimeEvent_Handler,
		},
		{
			MethodName: "DeleteEvent",
			Handler:    _EventService_DeleteEvent_Handler,
		},
		{
			MethodName: "JoinToEvent",
			Handler:    _EventService_JoinToEvent_Handler,
		},
		{
			MethodName: "LeaveEvent",
			Handler:    _EventService_LeaveEvent_Handler,
		},
		{
			MethodName: "SetRole",
			Handler:    _EventService_SetRole_Handler,
		},
		{
			MethodName: "GetEventMembersList",
			Handler:    _EventService_GetEventMembersList_Handler,
		},
		{
			MethodName: "GetTeamsByEventID",
			Handler:    _EventService_GetTeamsByEventID_Handler,
		},
		{
			MethodName: "StartTeamGame",
			Handler:    _EventService_StartTeamGame_Handler,
		},
		{
			MethodName: "FinishTeamGame",
			Handler:    _EventService_FinishTeamGame_Handler,
		},
		{
			MethodName: "AddTeamMemberStats",
			Handler:    _EventService_AddTeamMemberStats_Handler,
		},
		{
			MethodName: "GetTeamStats",
			Handler:    _EventService_GetTeamStats_Handler,
		},
		{
			MethodName: "GetTeamByID",
			Handler:    _EventService_GetTeamByID_Handler,
		},
		{
			MethodName: "AddUserToTeam",
			Handler:    _EventService_AddUserToTeam_Handler,
		},
		{
			MethodName: "RemoveUserFromTeam",
			Handler:    _EventService_RemoveUserFromTeam_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event.proto",
}
