// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/core/proto/event.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventId         string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UserCreateId    string                 `protobuf:"bytes,3,opt,name=user_create_id,json=userCreateId,proto3" json:"user_create_id,omitempty"`
	UserCount       int64                  `protobuf:"varint,4,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
	TimeStart       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"`
	TimeFinish      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=time_finish,json=timeFinish,proto3" json:"time_finish,omitempty"`
	CreateTime      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	EventTeamWinner string                 `protobuf:"bytes,8,opt,name=event_team_winner,json=eventTeamWinner,proto3" json:"event_team_winner,omitempty"`
	EventTeamLoser  string                 `protobuf:"bytes,9,opt,name=event_team_loser,json=eventTeamLoser,proto3" json:"event_team_loser,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_internal_core_proto_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetUserCreateId() string {
	if x != nil {
		return x.UserCreateId
	}
	return ""
}

func (x *Event) GetUserCount() int64 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

func (x *Event) GetTimeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeStart
	}
	return nil
}

func (x *Event) GetTimeFinish() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeFinish
	}
	return nil
}

func (x *Event) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Event) GetEventTeamWinner() string {
	if x != nil {
		return x.EventTeamWinner
	}
	return ""
}

func (x *Event) GetEventTeamLoser() string {
	if x != nil {
		return x.EventTeamLoser
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserEventId   string                 `protobuf:"bytes,1,opt,name=user_event_id,json=userEventId,proto3" json:"user_event_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClanId        string                 `protobuf:"bytes,3,opt,name=clan_id,json=clanId,proto3" json:"clan_id,omitempty"`
	TeamId        string                 `protobuf:"bytes,4,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_internal_core_proto_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetUserEventId() string {
	if x != nil {
		return x.UserEventId
	}
	return ""
}

func (x *User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *User) GetClanId() string {
	if x != nil {
		return x.ClanId
	}
	return ""
}

func (x *User) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type Game struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GameId           string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	EventId          string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	MapId            string                 `protobuf:"bytes,3,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	GameTeamWinnerId string                 `protobuf:"bytes,4,opt,name=game_team_winner_id,json=gameTeamWinnerId,proto3" json:"game_team_winner_id,omitempty"`
	GameTeamLoserId  string                 `protobuf:"bytes,5,opt,name=game_team_loser_id,json=gameTeamLoserId,proto3" json:"game_team_loser_id,omitempty"`
	TimeStart        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"`
	TimeFinish       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=time_finish,json=timeFinish,proto3" json:"time_finish,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Game) Reset() {
	*x = Game{}
	mi := &file_internal_core_proto_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{2}
}

func (x *Game) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *Game) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Game) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *Game) GetGameTeamWinnerId() string {
	if x != nil {
		return x.GameTeamWinnerId
	}
	return ""
}

func (x *Game) GetGameTeamLoserId() string {
	if x != nil {
		return x.GameTeamLoserId
	}
	return ""
}

func (x *Game) GetTimeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeStart
	}
	return nil
}

func (x *Game) GetTimeFinish() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeFinish
	}
	return nil
}

type GameUserStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GameUserStatsId string                 `protobuf:"bytes,1,opt,name=game_user_stats_id,json=gameUserStatsId,proto3" json:"game_user_stats_id,omitempty"`
	Game            *Game                  `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	User            *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Kills           int64                  `protobuf:"varint,4,opt,name=kills,proto3" json:"kills,omitempty"`
	Deaths          int64                  `protobuf:"varint,5,opt,name=deaths,proto3" json:"deaths,omitempty"`
	Points          int64                  `protobuf:"varint,6,opt,name=points,proto3" json:"points,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GameUserStats) Reset() {
	*x = GameUserStats{}
	mi := &file_internal_core_proto_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameUserStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameUserStats) ProtoMessage() {}

func (x *GameUserStats) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameUserStats.ProtoReflect.Descriptor instead.
func (*GameUserStats) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{3}
}

func (x *GameUserStats) GetGameUserStatsId() string {
	if x != nil {
		return x.GameUserStatsId
	}
	return ""
}

func (x *GameUserStats) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

func (x *GameUserStats) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GameUserStats) GetKills() int64 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *GameUserStats) GetDeaths() int64 {
	if x != nil {
		return x.Deaths
	}
	return 0
}

func (x *GameUserStats) GetPoints() int64 {
	if x != nil {
		return x.Points
	}
	return 0
}

type CreateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserCreateId  string                 `protobuf:"bytes,1,opt,name=user_create_id,json=userCreateId,proto3" json:"user_create_id,omitempty"`
	EventName     string                 `protobuf:"bytes,2,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	TimeStart     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_internal_core_proto_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{4}
}

func (x *CreateEventRequest) GetUserCreateId() string {
	if x != nil {
		return x.UserCreateId
	}
	return ""
}

func (x *CreateEventRequest) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *CreateEventRequest) GetTimeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeStart
	}
	return nil
}

type CreateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventResponse) Reset() {
	*x = CreateEventResponse{}
	mi := &file_internal_core_proto_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventResponse) ProtoMessage() {}

func (x *CreateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventResponse.ProtoReflect.Descriptor instead.
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{5}
}

func (x *CreateEventResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetEventsByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserCreateId  string                 `protobuf:"bytes,1,opt,name=user_create_id,json=userCreateId,proto3" json:"user_create_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsByUserIDRequest) Reset() {
	*x = GetEventsByUserIDRequest{}
	mi := &file_internal_core_proto_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsByUserIDRequest) ProtoMessage() {}

func (x *GetEventsByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsByUserIDRequest.ProtoReflect.Descriptor instead.
func (*GetEventsByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{6}
}

func (x *GetEventsByUserIDRequest) GetUserCreateId() string {
	if x != nil {
		return x.UserCreateId
	}
	return ""
}

type GetEventsByUserIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsByUserIDResponse) Reset() {
	*x = GetEventsByUserIDResponse{}
	mi := &file_internal_core_proto_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsByUserIDResponse) ProtoMessage() {}

func (x *GetEventsByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsByUserIDResponse.ProtoReflect.Descriptor instead.
func (*GetEventsByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{7}
}

func (x *GetEventsByUserIDResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetEventsByUserIDResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetEventsByEventNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventName     string                 `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsByEventNameRequest) Reset() {
	*x = GetEventsByEventNameRequest{}
	mi := &file_internal_core_proto_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsByEventNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsByEventNameRequest) ProtoMessage() {}

func (x *GetEventsByEventNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsByEventNameRequest.ProtoReflect.Descriptor instead.
func (*GetEventsByEventNameRequest) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{8}
}

func (x *GetEventsByEventNameRequest) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

type GetEventsByEventNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsByEventNameResponse) Reset() {
	*x = GetEventsByEventNameResponse{}
	mi := &file_internal_core_proto_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsByEventNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsByEventNameResponse) ProtoMessage() {}

func (x *GetEventsByEventNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsByEventNameResponse.ProtoReflect.Descriptor instead.
func (*GetEventsByEventNameResponse) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{9}
}

func (x *GetEventsByEventNameResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetEventsByEventNameResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateTimeEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserCreateId  string                 `protobuf:"bytes,2,opt,name=user_create_id,json=userCreateId,proto3" json:"user_create_id,omitempty"`
	NewTimeStart  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=new_time_start,json=newTimeStart,proto3" json:"new_time_start,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTimeEventRequest) Reset() {
	*x = UpdateTimeEventRequest{}
	mi := &file_internal_core_proto_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTimeEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTimeEventRequest) ProtoMessage() {}

func (x *UpdateTimeEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTimeEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateTimeEventRequest) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateTimeEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *UpdateTimeEventRequest) GetUserCreateId() string {
	if x != nil {
		return x.UserCreateId
	}
	return ""
}

func (x *UpdateTimeEventRequest) GetNewTimeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.NewTimeStart
	}
	return nil
}

type UpdateTimeEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTimeEventResponse) Reset() {
	*x = UpdateTimeEventResponse{}
	mi := &file_internal_core_proto_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTimeEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTimeEventResponse) ProtoMessage() {}

func (x *UpdateTimeEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTimeEventResponse.ProtoReflect.Descriptor instead.
func (*UpdateTimeEventResponse) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateTimeEventResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserCreateId  string                 `protobuf:"bytes,2,opt,name=user_create_id,json=userCreateId,proto3" json:"user_create_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventRequest) Reset() {
	*x = DeleteEventRequest{}
	mi := &file_internal_core_proto_event_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventRequest) ProtoMessage() {}

func (x *DeleteEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteEventRequest) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *DeleteEventRequest) GetUserCreateId() string {
	if x != nil {
		return x.UserCreateId
	}
	return ""
}

type DeleteEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventResponse) Reset() {
	*x = DeleteEventResponse{}
	mi := &file_internal_core_proto_event_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventResponse) ProtoMessage() {}

func (x *DeleteEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteEventResponse) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteEventResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type JoinToEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	JoinTime      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=join_time,json=joinTime,proto3" json:"join_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinToEventRequest) Reset() {
	*x = JoinToEventRequest{}
	mi := &file_internal_core_proto_event_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinToEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinToEventRequest) ProtoMessage() {}

func (x *JoinToEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinToEventRequest.ProtoReflect.Descriptor instead.
func (*JoinToEventRequest) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{14}
}

func (x *JoinToEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *JoinToEventRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JoinToEventRequest) GetJoinTime() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinTime
	}
	return nil
}

type JoinToEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinToEventResponse) Reset() {
	*x = JoinToEventResponse{}
	mi := &file_internal_core_proto_event_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinToEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinToEventResponse) ProtoMessage() {}

func (x *JoinToEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinToEventResponse.ProtoReflect.Descriptor instead.
func (*JoinToEventResponse) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{15}
}

func (x *JoinToEventResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LeaveEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveEventRequest) Reset() {
	*x = LeaveEventRequest{}
	mi := &file_internal_core_proto_event_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveEventRequest) ProtoMessage() {}

func (x *LeaveEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveEventRequest.ProtoReflect.Descriptor instead.
func (*LeaveEventRequest) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{16}
}

func (x *LeaveEventRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LeaveEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type LeaveEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveEventResponse) Reset() {
	*x = LeaveEventResponse{}
	mi := &file_internal_core_proto_event_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveEventResponse) ProtoMessage() {}

func (x *LeaveEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveEventResponse.ProtoReflect.Descriptor instead.
func (*LeaveEventResponse) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{17}
}

func (x *LeaveEventResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CreateGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	MapId         string                 `protobuf:"bytes,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	TimeStart     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameRequest) Reset() {
	*x = CreateGameRequest{}
	mi := &file_internal_core_proto_event_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{18}
}

func (x *CreateGameRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CreateGameRequest) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *CreateGameRequest) GetTimeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeStart
	}
	return nil
}

type CreateGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameResponse) Reset() {
	*x = CreateGameResponse{}
	mi := &file_internal_core_proto_event_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameResponse) ProtoMessage() {}

func (x *CreateGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameResponse.ProtoReflect.Descriptor instead.
func (*CreateGameResponse) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{19}
}

func (x *CreateGameResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetGameByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameByIDRequest) Reset() {
	*x = GetGameByIDRequest{}
	mi := &file_internal_core_proto_event_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameByIDRequest) ProtoMessage() {}

func (x *GetGameByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameByIDRequest.ProtoReflect.Descriptor instead.
func (*GetGameByIDRequest) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{20}
}

func (x *GetGameByIDRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type GetGameByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *Game                  `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameByIDResponse) Reset() {
	*x = GetGameByIDResponse{}
	mi := &file_internal_core_proto_event_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameByIDResponse) ProtoMessage() {}

func (x *GetGameByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameByIDResponse.ProtoReflect.Descriptor instead.
func (*GetGameByIDResponse) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{21}
}

func (x *GetGameByIDResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

func (x *GetGameByIDResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetGamesByEventIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGamesByEventIDRequest) Reset() {
	*x = GetGamesByEventIDRequest{}
	mi := &file_internal_core_proto_event_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGamesByEventIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGamesByEventIDRequest) ProtoMessage() {}

func (x *GetGamesByEventIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGamesByEventIDRequest.ProtoReflect.Descriptor instead.
func (*GetGamesByEventIDRequest) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{22}
}

func (x *GetGamesByEventIDRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type GetGamesByEventIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Games         []*Game                `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGamesByEventIDResponse) Reset() {
	*x = GetGamesByEventIDResponse{}
	mi := &file_internal_core_proto_event_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGamesByEventIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGamesByEventIDResponse) ProtoMessage() {}

func (x *GetGamesByEventIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGamesByEventIDResponse.ProtoReflect.Descriptor instead.
func (*GetGamesByEventIDResponse) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{23}
}

func (x *GetGamesByEventIDResponse) GetGames() []*Game {
	if x != nil {
		return x.Games
	}
	return nil
}

func (x *GetGamesByEventIDResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateGameWinnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	WinnerTeamId  string                 `protobuf:"bytes,2,opt,name=winner_team_id,json=winnerTeamId,proto3" json:"winner_team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGameWinnerRequest) Reset() {
	*x = UpdateGameWinnerRequest{}
	mi := &file_internal_core_proto_event_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGameWinnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameWinnerRequest) ProtoMessage() {}

func (x *UpdateGameWinnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameWinnerRequest.ProtoReflect.Descriptor instead.
func (*UpdateGameWinnerRequest) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateGameWinnerRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *UpdateGameWinnerRequest) GetWinnerTeamId() string {
	if x != nil {
		return x.WinnerTeamId
	}
	return ""
}

type UpdateGameWinnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGameWinnerResponse) Reset() {
	*x = UpdateGameWinnerResponse{}
	mi := &file_internal_core_proto_event_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGameWinnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameWinnerResponse) ProtoMessage() {}

func (x *UpdateGameWinnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameWinnerResponse.ProtoReflect.Descriptor instead.
func (*UpdateGameWinnerResponse) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateGameWinnerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateGameLoserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	LoserTeamId   string                 `protobuf:"bytes,2,opt,name=loser_team_id,json=loserTeamId,proto3" json:"loser_team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGameLoserRequest) Reset() {
	*x = UpdateGameLoserRequest{}
	mi := &file_internal_core_proto_event_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGameLoserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameLoserRequest) ProtoMessage() {}

func (x *UpdateGameLoserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameLoserRequest.ProtoReflect.Descriptor instead.
func (*UpdateGameLoserRequest) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateGameLoserRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *UpdateGameLoserRequest) GetLoserTeamId() string {
	if x != nil {
		return x.LoserTeamId
	}
	return ""
}

type UpdateGameLoserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGameLoserResponse) Reset() {
	*x = UpdateGameLoserResponse{}
	mi := &file_internal_core_proto_event_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGameLoserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameLoserResponse) ProtoMessage() {}

func (x *UpdateGameLoserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameLoserResponse.ProtoReflect.Descriptor instead.
func (*UpdateGameLoserResponse) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateGameLoserResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FinishGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	TimeFinish    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time_finish,json=timeFinish,proto3" json:"time_finish,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishGameRequest) Reset() {
	*x = FinishGameRequest{}
	mi := &file_internal_core_proto_event_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishGameRequest) ProtoMessage() {}

func (x *FinishGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishGameRequest.ProtoReflect.Descriptor instead.
func (*FinishGameRequest) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{28}
}

func (x *FinishGameRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *FinishGameRequest) GetTimeFinish() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeFinish
	}
	return nil
}

type FinishGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishGameResponse) Reset() {
	*x = FinishGameResponse{}
	mi := &file_internal_core_proto_event_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishGameResponse) ProtoMessage() {}

func (x *FinishGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishGameResponse.ProtoReflect.Descriptor instead.
func (*FinishGameResponse) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{29}
}

func (x *FinishGameResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGameRequest) Reset() {
	*x = DeleteGameRequest{}
	mi := &file_internal_core_proto_event_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGameRequest) ProtoMessage() {}

func (x *DeleteGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGameRequest.ProtoReflect.Descriptor instead.
func (*DeleteGameRequest) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{30}
}

func (x *DeleteGameRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type DeleteGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGameResponse) Reset() {
	*x = DeleteGameResponse{}
	mi := &file_internal_core_proto_event_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGameResponse) ProtoMessage() {}

func (x *DeleteGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGameResponse.ProtoReflect.Descriptor instead.
func (*DeleteGameResponse) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{31}
}

func (x *DeleteGameResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AddUserStatsToGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Kills         int64                  `protobuf:"varint,3,opt,name=kills,proto3" json:"kills,omitempty"`
	Deaths        int64                  `protobuf:"varint,4,opt,name=deaths,proto3" json:"deaths,omitempty"`
	Points        int64                  `protobuf:"varint,5,opt,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserStatsToGameRequest) Reset() {
	*x = AddUserStatsToGameRequest{}
	mi := &file_internal_core_proto_event_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserStatsToGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserStatsToGameRequest) ProtoMessage() {}

func (x *AddUserStatsToGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserStatsToGameRequest.ProtoReflect.Descriptor instead.
func (*AddUserStatsToGameRequest) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{32}
}

func (x *AddUserStatsToGameRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *AddUserStatsToGameRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddUserStatsToGameRequest) GetKills() int64 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *AddUserStatsToGameRequest) GetDeaths() int64 {
	if x != nil {
		return x.Deaths
	}
	return 0
}

func (x *AddUserStatsToGameRequest) GetPoints() int64 {
	if x != nil {
		return x.Points
	}
	return 0
}

type AddUserStatsToGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserStatsToGameResponse) Reset() {
	*x = AddUserStatsToGameResponse{}
	mi := &file_internal_core_proto_event_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserStatsToGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserStatsToGameResponse) ProtoMessage() {}

func (x *AddUserStatsToGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserStatsToGameResponse.ProtoReflect.Descriptor instead.
func (*AddUserStatsToGameResponse) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{33}
}

func (x *AddUserStatsToGameResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetGameStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameStatsRequest) Reset() {
	*x = GetGameStatsRequest{}
	mi := &file_internal_core_proto_event_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameStatsRequest) ProtoMessage() {}

func (x *GetGameStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameStatsRequest.ProtoReflect.Descriptor instead.
func (*GetGameStatsRequest) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{34}
}

func (x *GetGameStatsRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type GetGameStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*GameUserStats       `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameStatsResponse) Reset() {
	*x = GetGameStatsResponse{}
	mi := &file_internal_core_proto_event_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameStatsResponse) ProtoMessage() {}

func (x *GetGameStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_proto_event_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameStatsResponse.ProtoReflect.Descriptor instead.
func (*GetGameStatsResponse) Descriptor() ([]byte, []int) {
	return file_internal_core_proto_event_proto_rawDescGZIP(), []int{35}
}

func (x *GetGameStatsResponse) GetStats() []*GameUserStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *GetGameStatsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_core_proto_event_proto protoreflect.FileDescriptor

const file_internal_core_proto_event_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/core/proto/event.proto\x12\x05event\x1a\x1fgoogle/protobuf/timestamp.proto\"\x86\x03\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12$\n" +
	"\x0euser_create_id\x18\x03 \x01(\tR\fuserCreateId\x12\x1d\n" +
	"\n" +
	"user_count\x18\x04 \x01(\x03R\tuserCount\x129\n" +
	"\n" +
	"time_start\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimeStart\x12;\n" +
	"\vtime_finish\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"timeFinish\x12;\n" +
	"\vcreate_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12*\n" +
	"\x11event_team_winner\x18\b \x01(\tR\x0feventTeamWinner\x12(\n" +
	"\x10event_team_loser\x18\t \x01(\tR\x0eeventTeamLoser\"\x89\x01\n" +
	"\x04User\x12\"\n" +
	"\ruser_event_id\x18\x01 \x01(\tR\vuserEventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\aclan_id\x18\x03 \x01(\tR\x06clanId\x12\x17\n" +
	"\ateam_id\x18\x04 \x01(\tR\x06teamId\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\"\xa5\x02\n" +
	"\x04Game\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x15\n" +
	"\x06map_id\x18\x03 \x01(\tR\x05mapId\x12-\n" +
	"\x13game_team_winner_id\x18\x04 \x01(\tR\x10gameTeamWinnerId\x12+\n" +
	"\x12game_team_loser_id\x18\x05 \x01(\tR\x0fgameTeamLoserId\x129\n" +
	"\n" +
	"time_start\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimeStart\x12;\n" +
	"\vtime_finish\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"timeFinish\"\xc4\x01\n" +
	"\rGameUserStats\x12+\n" +
	"\x12game_user_stats_id\x18\x01 \x01(\tR\x0fgameUserStatsId\x12\x1f\n" +
	"\x04game\x18\x02 \x01(\v2\v.event.GameR\x04game\x12\x1f\n" +
	"\x04user\x18\x03 \x01(\v2\v.event.UserR\x04user\x12\x14\n" +
	"\x05kills\x18\x04 \x01(\x03R\x05kills\x12\x16\n" +
	"\x06deaths\x18\x05 \x01(\x03R\x06deaths\x12\x16\n" +
	"\x06points\x18\x06 \x01(\x03R\x06points\"\x94\x01\n" +
	"\x12CreateEventRequest\x12$\n" +
	"\x0euser_create_id\x18\x01 \x01(\tR\fuserCreateId\x12\x1d\n" +
	"\n" +
	"event_name\x18\x02 \x01(\tR\teventName\x129\n" +
	"\n" +
	"time_start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimeStart\"+\n" +
	"\x13CreateEventResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"@\n" +
	"\x18GetEventsByUserIDRequest\x12$\n" +
	"\x0euser_create_id\x18\x01 \x01(\tR\fuserCreateId\"W\n" +
	"\x19GetEventsByUserIDResponse\x12$\n" +
	"\x06events\x18\x01 \x03(\v2\f.event.EventR\x06events\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"<\n" +
	"\x1bGetEventsByEventNameRequest\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\"Z\n" +
	"\x1cGetEventsByEventNameResponse\x12$\n" +
	"\x06events\x18\x01 \x03(\v2\f.event.EventR\x06events\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x9b\x01\n" +
	"\x16UpdateTimeEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12$\n" +
	"\x0euser_create_id\x18\x02 \x01(\tR\fuserCreateId\x12@\n" +
	"\x0enew_time_start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\fnewTimeStart\"/\n" +
	"\x17UpdateTimeEventResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"U\n" +
	"\x12DeleteEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12$\n" +
	"\x0euser_create_id\x18\x02 \x01(\tR\fuserCreateId\"+\n" +
	"\x13DeleteEventResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x81\x01\n" +
	"\x12JoinToEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x127\n" +
	"\tjoin_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinTime\"+\n" +
	"\x13JoinToEventResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"G\n" +
	"\x11LeaveEventRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\"*\n" +
	"\x12LeaveEventResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x80\x01\n" +
	"\x11CreateGameRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\tR\x05mapId\x129\n" +
	"\n" +
	"time_start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimeStart\"*\n" +
	"\x12CreateGameResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"-\n" +
	"\x12GetGameByIDRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\"L\n" +
	"\x13GetGameByIDResponse\x12\x1f\n" +
	"\x04game\x18\x01 \x01(\v2\v.event.GameR\x04game\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"5\n" +
	"\x18GetGamesByEventIDRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"T\n" +
	"\x19GetGamesByEventIDResponse\x12!\n" +
	"\x05games\x18\x01 \x03(\v2\v.event.GameR\x05games\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"X\n" +
	"\x17UpdateGameWinnerRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12$\n" +
	"\x0ewinner_team_id\x18\x02 \x01(\tR\fwinnerTeamId\"0\n" +
	"\x18UpdateGameWinnerResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"U\n" +
	"\x16UpdateGameLoserRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\"\n" +
	"\rloser_team_id\x18\x02 \x01(\tR\vloserTeamId\"/\n" +
	"\x17UpdateGameLoserResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"i\n" +
	"\x11FinishGameRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12;\n" +
	"\vtime_finish\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"timeFinish\"*\n" +
	"\x12FinishGameResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\",\n" +
	"\x11DeleteGameRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\"*\n" +
	"\x12DeleteGameResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x93\x01\n" +
	"\x19AddUserStatsToGameRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05kills\x18\x03 \x01(\x03R\x05kills\x12\x16\n" +
	"\x06deaths\x18\x04 \x01(\x03R\x06deaths\x12\x16\n" +
	"\x06points\x18\x05 \x01(\x03R\x06points\"2\n" +
	"\x1aAddUserStatsToGameResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\".\n" +
	"\x13GetGameStatsRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\"X\n" +
	"\x14GetGameStatsResponse\x12*\n" +
	"\x05stats\x18\x01 \x03(\v2\x14.event.GameUserStatsR\x05stats\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xe0\t\n" +
	"\fEventService\x12D\n" +
	"\vCreateEvent\x12\x19.event.CreateEventRequest\x1a\x1a.event.CreateEventResponse\x12V\n" +
	"\x11GetEventsByUserID\x12\x1f.event.GetEventsByUserIDRequest\x1a .event.GetEventsByUserIDResponse\x12_\n" +
	"\x14GetEventsByEventName\x12\".event.GetEventsByEventNameRequest\x1a#.event.GetEventsByEventNameResponse\x12P\n" +
	"\x0fUpdateTimeEvent\x12\x1d.event.UpdateTimeEventRequest\x1a\x1e.event.UpdateTimeEventResponse\x12D\n" +
	"\vDeleteEvent\x12\x19.event.DeleteEventRequest\x1a\x1a.event.DeleteEventResponse\x12D\n" +
	"\vJoinToEvent\x12\x19.event.JoinToEventRequest\x1a\x1a.event.JoinToEventResponse\x12A\n" +
	"\n" +
	"LeaveEvent\x12\x18.event.LeaveEventRequest\x1a\x19.event.LeaveEventResponse\x12A\n" +
	"\n" +
	"CreateGame\x12\x18.event.CreateGameRequest\x1a\x19.event.CreateGameResponse\x12D\n" +
	"\vGetGameByID\x12\x19.event.GetGameByIDRequest\x1a\x1a.event.GetGameByIDResponse\x12V\n" +
	"\x11GetGamesByEventID\x12\x1f.event.GetGamesByEventIDRequest\x1a .event.GetGamesByEventIDResponse\x12S\n" +
	"\x10UpdateGameWinner\x12\x1e.event.UpdateGameWinnerRequest\x1a\x1f.event.UpdateGameWinnerResponse\x12P\n" +
	"\x0fUpdateGameLoser\x12\x1d.event.UpdateGameLoserRequest\x1a\x1e.event.UpdateGameLoserResponse\x12A\n" +
	"\n" +
	"FinishGame\x12\x18.event.FinishGameRequest\x1a\x19.event.FinishGameResponse\x12A\n" +
	"\n" +
	"DeleteGame\x12\x18.event.DeleteGameRequest\x1a\x19.event.DeleteGameResponse\x12Y\n" +
	"\x12AddUserStatsToGame\x12 .event.AddUserStatsToGameRequest\x1a!.event.AddUserStatsToGameResponse\x12G\n" +
	"\fGetGameStats\x12\x1a.event.GetGameStatsRequest\x1a\x1b.event.GetGameStatsResponseB#Z!event-service/internal/core/protob\x06proto3"

var (
	file_internal_core_proto_event_proto_rawDescOnce sync.Once
	file_internal_core_proto_event_proto_rawDescData []byte
)

func file_internal_core_proto_event_proto_rawDescGZIP() []byte {
	file_internal_core_proto_event_proto_rawDescOnce.Do(func() {
		file_internal_core_proto_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_core_proto_event_proto_rawDesc), len(file_internal_core_proto_event_proto_rawDesc)))
	})
	return file_internal_core_proto_event_proto_rawDescData
}

var file_internal_core_proto_event_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_internal_core_proto_event_proto_goTypes = []any{
	(*Event)(nil),                        // 0: event.Event
	(*User)(nil),                         // 1: event.User
	(*Game)(nil),                         // 2: event.Game
	(*GameUserStats)(nil),                // 3: event.GameUserStats
	(*CreateEventRequest)(nil),           // 4: event.CreateEventRequest
	(*CreateEventResponse)(nil),          // 5: event.CreateEventResponse
	(*GetEventsByUserIDRequest)(nil),     // 6: event.GetEventsByUserIDRequest
	(*GetEventsByUserIDResponse)(nil),    // 7: event.GetEventsByUserIDResponse
	(*GetEventsByEventNameRequest)(nil),  // 8: event.GetEventsByEventNameRequest
	(*GetEventsByEventNameResponse)(nil), // 9: event.GetEventsByEventNameResponse
	(*UpdateTimeEventRequest)(nil),       // 10: event.UpdateTimeEventRequest
	(*UpdateTimeEventResponse)(nil),      // 11: event.UpdateTimeEventResponse
	(*DeleteEventRequest)(nil),           // 12: event.DeleteEventRequest
	(*DeleteEventResponse)(nil),          // 13: event.DeleteEventResponse
	(*JoinToEventRequest)(nil),           // 14: event.JoinToEventRequest
	(*JoinToEventResponse)(nil),          // 15: event.JoinToEventResponse
	(*LeaveEventRequest)(nil),            // 16: event.LeaveEventRequest
	(*LeaveEventResponse)(nil),           // 17: event.LeaveEventResponse
	(*CreateGameRequest)(nil),            // 18: event.CreateGameRequest
	(*CreateGameResponse)(nil),           // 19: event.CreateGameResponse
	(*GetGameByIDRequest)(nil),           // 20: event.GetGameByIDRequest
	(*GetGameByIDResponse)(nil),          // 21: event.GetGameByIDResponse
	(*GetGamesByEventIDRequest)(nil),     // 22: event.GetGamesByEventIDRequest
	(*GetGamesByEventIDResponse)(nil),    // 23: event.GetGamesByEventIDResponse
	(*UpdateGameWinnerRequest)(nil),      // 24: event.UpdateGameWinnerRequest
	(*UpdateGameWinnerResponse)(nil),     // 25: event.UpdateGameWinnerResponse
	(*UpdateGameLoserRequest)(nil),       // 26: event.UpdateGameLoserRequest
	(*UpdateGameLoserResponse)(nil),      // 27: event.UpdateGameLoserResponse
	(*FinishGameRequest)(nil),            // 28: event.FinishGameRequest
	(*FinishGameResponse)(nil),           // 29: event.FinishGameResponse
	(*DeleteGameRequest)(nil),            // 30: event.DeleteGameRequest
	(*DeleteGameResponse)(nil),           // 31: event.DeleteGameResponse
	(*AddUserStatsToGameRequest)(nil),    // 32: event.AddUserStatsToGameRequest
	(*AddUserStatsToGameResponse)(nil),   // 33: event.AddUserStatsToGameResponse
	(*GetGameStatsRequest)(nil),          // 34: event.GetGameStatsRequest
	(*GetGameStatsResponse)(nil),         // 35: event.GetGameStatsResponse
	(*timestamppb.Timestamp)(nil),        // 36: google.protobuf.Timestamp
}
var file_internal_core_proto_event_proto_depIdxs = []int32{
	36, // 0: event.Event.time_start:type_name -> google.protobuf.Timestamp
	36, // 1: event.Event.time_finish:type_name -> google.protobuf.Timestamp
	36, // 2: event.Event.create_time:type_name -> google.protobuf.Timestamp
	36, // 3: event.Game.time_start:type_name -> google.protobuf.Timestamp
	36, // 4: event.Game.time_finish:type_name -> google.protobuf.Timestamp
	2,  // 5: event.GameUserStats.game:type_name -> event.Game
	1,  // 6: event.GameUserStats.user:type_name -> event.User
	36, // 7: event.CreateEventRequest.time_start:type_name -> google.protobuf.Timestamp
	0,  // 8: event.GetEventsByUserIDResponse.events:type_name -> event.Event
	0,  // 9: event.GetEventsByEventNameResponse.events:type_name -> event.Event
	36, // 10: event.UpdateTimeEventRequest.new_time_start:type_name -> google.protobuf.Timestamp
	36, // 11: event.JoinToEventRequest.join_time:type_name -> google.protobuf.Timestamp
	36, // 12: event.CreateGameRequest.time_start:type_name -> google.protobuf.Timestamp
	2,  // 13: event.GetGameByIDResponse.game:type_name -> event.Game
	2,  // 14: event.GetGamesByEventIDResponse.games:type_name -> event.Game
	36, // 15: event.FinishGameRequest.time_finish:type_name -> google.protobuf.Timestamp
	3,  // 16: event.GetGameStatsResponse.stats:type_name -> event.GameUserStats
	4,  // 17: event.EventService.CreateEvent:input_type -> event.CreateEventRequest
	6,  // 18: event.EventService.GetEventsByUserID:input_type -> event.GetEventsByUserIDRequest
	8,  // 19: event.EventService.GetEventsByEventName:input_type -> event.GetEventsByEventNameRequest
	10, // 20: event.EventService.UpdateTimeEvent:input_type -> event.UpdateTimeEventRequest
	12, // 21: event.EventService.DeleteEvent:input_type -> event.DeleteEventRequest
	14, // 22: event.EventService.JoinToEvent:input_type -> event.JoinToEventRequest
	16, // 23: event.EventService.LeaveEvent:input_type -> event.LeaveEventRequest
	18, // 24: event.EventService.CreateGame:input_type -> event.CreateGameRequest
	20, // 25: event.EventService.GetGameByID:input_type -> event.GetGameByIDRequest
	22, // 26: event.EventService.GetGamesByEventID:input_type -> event.GetGamesByEventIDRequest
	24, // 27: event.EventService.UpdateGameWinner:input_type -> event.UpdateGameWinnerRequest
	26, // 28: event.EventService.UpdateGameLoser:input_type -> event.UpdateGameLoserRequest
	28, // 29: event.EventService.FinishGame:input_type -> event.FinishGameRequest
	30, // 30: event.EventService.DeleteGame:input_type -> event.DeleteGameRequest
	32, // 31: event.EventService.AddUserStatsToGame:input_type -> event.AddUserStatsToGameRequest
	34, // 32: event.EventService.GetGameStats:input_type -> event.GetGameStatsRequest
	5,  // 33: event.EventService.CreateEvent:output_type -> event.CreateEventResponse
	7,  // 34: event.EventService.GetEventsByUserID:output_type -> event.GetEventsByUserIDResponse
	9,  // 35: event.EventService.GetEventsByEventName:output_type -> event.GetEventsByEventNameResponse
	11, // 36: event.EventService.UpdateTimeEvent:output_type -> event.UpdateTimeEventResponse
	13, // 37: event.EventService.DeleteEvent:output_type -> event.DeleteEventResponse
	15, // 38: event.EventService.JoinToEvent:output_type -> event.JoinToEventResponse
	17, // 39: event.EventService.LeaveEvent:output_type -> event.LeaveEventResponse
	19, // 40: event.EventService.CreateGame:output_type -> event.CreateGameResponse
	21, // 41: event.EventService.GetGameByID:output_type -> event.GetGameByIDResponse
	23, // 42: event.EventService.GetGamesByEventID:output_type -> event.GetGamesByEventIDResponse
	25, // 43: event.EventService.UpdateGameWinner:output_type -> event.UpdateGameWinnerResponse
	27, // 44: event.EventService.UpdateGameLoser:output_type -> event.UpdateGameLoserResponse
	29, // 45: event.EventService.FinishGame:output_type -> event.FinishGameResponse
	31, // 46: event.EventService.DeleteGame:output_type -> event.DeleteGameResponse
	33, // 47: event.EventService.AddUserStatsToGame:output_type -> event.AddUserStatsToGameResponse
	35, // 48: event.EventService.GetGameStats:output_type -> event.GetGameStatsResponse
	33, // [33:49] is the sub-list for method output_type
	17, // [17:33] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_internal_core_proto_event_proto_init() }
func file_internal_core_proto_event_proto_init() {
	if File_internal_core_proto_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_core_proto_event_proto_rawDesc), len(file_internal_core_proto_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_core_proto_event_proto_goTypes,
		DependencyIndexes: file_internal_core_proto_event_proto_depIdxs,
		MessageInfos:      file_internal_core_proto_event_proto_msgTypes,
	}.Build()
	File_internal_core_proto_event_proto = out.File
	file_internal_core_proto_event_proto_goTypes = nil
	file_internal_core_proto_event_proto_depIdxs = nil
}
