// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: event.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventService_CreateEvent_FullMethodName                    = "/event.EventService/CreateEvent"
	EventService_GetEventsByCreatorId_FullMethodName           = "/event.EventService/GetEventsByCreatorId"
	EventService_GetLastEventByCreatorId_FullMethodName        = "/event.EventService/GetLastEventByCreatorId"
	EventService_GetEventsByEventName_FullMethodName           = "/event.EventService/GetEventsByEventName"
	EventService_GetUnfinishedEventsByUserID_FullMethodName    = "/event.EventService/GetUnfinishedEventsByUserID"
	EventService_GetUnfinishedEventsByEventName_FullMethodName = "/event.EventService/GetUnfinishedEventsByEventName"
	EventService_UpdateTimeEvent_FullMethodName                = "/event.EventService/UpdateTimeEvent"
	EventService_DeleteEvent_FullMethodName                    = "/event.EventService/DeleteEvent"
	EventService_JoinToEvent_FullMethodName                    = "/event.EventService/JoinToEvent"
	EventService_LeaveEvent_FullMethodName                     = "/event.EventService/LeaveEvent"
	EventService_SetRole_FullMethodName                        = "/event.EventService/SetRole"
	EventService_CreateTeamsForEvent_FullMethodName            = "/event.EventService/CreateTeamsForEvent"
	EventService_GetTeamsByEventID_FullMethodName              = "/event.EventService/GetTeamsByEventID"
	EventService_StartEvent_FullMethodName                     = "/event.EventService/StartEvent"
	EventService_FinishEvent_FullMethodName                    = "/event.EventService/FinishEvent"
	EventService_CreateGame_FullMethodName                     = "/event.EventService/CreateGame"
	EventService_GetGameByID_FullMethodName                    = "/event.EventService/GetGameByID"
	EventService_GetGamesByEventID_FullMethodName              = "/event.EventService/GetGamesByEventID"
	EventService_UpdateGameWinner_FullMethodName               = "/event.EventService/UpdateGameWinner"
	EventService_UpdateGameLoser_FullMethodName                = "/event.EventService/UpdateGameLoser"
	EventService_FinishGame_FullMethodName                     = "/event.EventService/FinishGame"
	EventService_AddUserStatsToGame_FullMethodName             = "/event.EventService/AddUserStatsToGame"
	EventService_GetGameStats_FullMethodName                   = "/event.EventService/GetGameStats"
	EventService_GetTeamByID_FullMethodName                    = "/event.EventService/GetTeamByID"
	EventService_AddUserToTeam_FullMethodName                  = "/event.EventService/AddUserToTeam"
	EventService_RemoveUserFromTeam_FullMethodName             = "/event.EventService/RemoveUserFromTeam"
)

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventServiceClient interface {
	CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*CreateEventResponse, error)
	GetEventsByCreatorId(ctx context.Context, in *GetEventsByCreatorIdRequest, opts ...grpc.CallOption) (*GetEventsByCreatorIdResponse, error)
	GetLastEventByCreatorId(ctx context.Context, in *GetLastEventByCreatorIdRequest, opts ...grpc.CallOption) (*GetLastEventByCreatorIdResponse, error)
	GetEventsByEventName(ctx context.Context, in *GetEventsByEventNameRequest, opts ...grpc.CallOption) (*GetEventsByEventNameResponse, error)
	GetUnfinishedEventsByUserID(ctx context.Context, in *GetUnfinishedEventsByUserIDRequest, opts ...grpc.CallOption) (*GetUnfinishedEventsByUserIDResponse, error)
	GetUnfinishedEventsByEventName(ctx context.Context, in *GetUnfinishedEventsByEventNameRequest, opts ...grpc.CallOption) (*GetUnfinishedEventsByEventNameResponse, error)
	UpdateTimeEvent(ctx context.Context, in *UpdateTimeEventRequest, opts ...grpc.CallOption) (*UpdateTimeEventResponse, error)
	DeleteEvent(ctx context.Context, in *DeleteEventRequest, opts ...grpc.CallOption) (*DeleteEventResponse, error)
	JoinToEvent(ctx context.Context, in *JoinToEventRequest, opts ...grpc.CallOption) (*JoinToEventResponse, error)
	LeaveEvent(ctx context.Context, in *LeaveEventRequest, opts ...grpc.CallOption) (*LeaveEventResponse, error)
	SetRole(ctx context.Context, in *SetRoleRequest, opts ...grpc.CallOption) (*SetRoleResponse, error)
	CreateTeamsForEvent(ctx context.Context, in *CreateTeamsForEventRequest, opts ...grpc.CallOption) (*CreateTeamsForEventResponse, error)
	GetTeamsByEventID(ctx context.Context, in *GetTeamsByEventIDRequest, opts ...grpc.CallOption) (*GetTeamsByEventIDResponse, error)
	StartEvent(ctx context.Context, in *StartEventRequest, opts ...grpc.CallOption) (*StartEventResponse, error)
	FinishEvent(ctx context.Context, in *FinishEventRequest, opts ...grpc.CallOption) (*FinishEventResponse, error)
	CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*CreateGameResponse, error)
	GetGameByID(ctx context.Context, in *GetGameByIDRequest, opts ...grpc.CallOption) (*GetGameByIDResponse, error)
	GetGamesByEventID(ctx context.Context, in *GetGamesByEventIDRequest, opts ...grpc.CallOption) (*GetGamesByEventIDResponse, error)
	UpdateGameWinner(ctx context.Context, in *UpdateGameWinnerRequest, opts ...grpc.CallOption) (*UpdateGameWinnerResponse, error)
	UpdateGameLoser(ctx context.Context, in *UpdateGameLoserRequest, opts ...grpc.CallOption) (*UpdateGameLoserResponse, error)
	FinishGame(ctx context.Context, in *FinishGameRequest, opts ...grpc.CallOption) (*FinishGameResponse, error)
	AddUserStatsToGame(ctx context.Context, in *AddUserStatsToGameRequest, opts ...grpc.CallOption) (*AddUserStatsToGameResponse, error)
	GetGameStats(ctx context.Context, in *GetGameStatsRequest, opts ...grpc.CallOption) (*GetGameStatsResponse, error)
	GetTeamByID(ctx context.Context, in *GetTeamByIDRequest, opts ...grpc.CallOption) (*GetTeamByIDResponse, error)
	AddUserToTeam(ctx context.Context, in *AddUserToTeamRequest, opts ...grpc.CallOption) (*AddUserToTeamResponse, error)
	RemoveUserFromTeam(ctx context.Context, in *RemoveUserFromTeamRequest, opts ...grpc.CallOption) (*RemoveUserFromTeamResponse, error)
}

type eventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventServiceClient(cc grpc.ClientConnInterface) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*CreateEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEventResponse)
	err := c.cc.Invoke(ctx, EventService_CreateEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetEventsByCreatorId(ctx context.Context, in *GetEventsByCreatorIdRequest, opts ...grpc.CallOption) (*GetEventsByCreatorIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventsByCreatorIdResponse)
	err := c.cc.Invoke(ctx, EventService_GetEventsByCreatorId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetLastEventByCreatorId(ctx context.Context, in *GetLastEventByCreatorIdRequest, opts ...grpc.CallOption) (*GetLastEventByCreatorIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLastEventByCreatorIdResponse)
	err := c.cc.Invoke(ctx, EventService_GetLastEventByCreatorId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetEventsByEventName(ctx context.Context, in *GetEventsByEventNameRequest, opts ...grpc.CallOption) (*GetEventsByEventNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventsByEventNameResponse)
	err := c.cc.Invoke(ctx, EventService_GetEventsByEventName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetUnfinishedEventsByUserID(ctx context.Context, in *GetUnfinishedEventsByUserIDRequest, opts ...grpc.CallOption) (*GetUnfinishedEventsByUserIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUnfinishedEventsByUserIDResponse)
	err := c.cc.Invoke(ctx, EventService_GetUnfinishedEventsByUserID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetUnfinishedEventsByEventName(ctx context.Context, in *GetUnfinishedEventsByEventNameRequest, opts ...grpc.CallOption) (*GetUnfinishedEventsByEventNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUnfinishedEventsByEventNameResponse)
	err := c.cc.Invoke(ctx, EventService_GetUnfinishedEventsByEventName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) UpdateTimeEvent(ctx context.Context, in *UpdateTimeEventRequest, opts ...grpc.CallOption) (*UpdateTimeEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTimeEventResponse)
	err := c.cc.Invoke(ctx, EventService_UpdateTimeEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) DeleteEvent(ctx context.Context, in *DeleteEventRequest, opts ...grpc.CallOption) (*DeleteEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEventResponse)
	err := c.cc.Invoke(ctx, EventService_DeleteEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) JoinToEvent(ctx context.Context, in *JoinToEventRequest, opts ...grpc.CallOption) (*JoinToEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinToEventResponse)
	err := c.cc.Invoke(ctx, EventService_JoinToEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) LeaveEvent(ctx context.Context, in *LeaveEventRequest, opts ...grpc.CallOption) (*LeaveEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveEventResponse)
	err := c.cc.Invoke(ctx, EventService_LeaveEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) SetRole(ctx context.Context, in *SetRoleRequest, opts ...grpc.CallOption) (*SetRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetRoleResponse)
	err := c.cc.Invoke(ctx, EventService_SetRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) CreateTeamsForEvent(ctx context.Context, in *CreateTeamsForEventRequest, opts ...grpc.CallOption) (*CreateTeamsForEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTeamsForEventResponse)
	err := c.cc.Invoke(ctx, EventService_CreateTeamsForEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetTeamsByEventID(ctx context.Context, in *GetTeamsByEventIDRequest, opts ...grpc.CallOption) (*GetTeamsByEventIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTeamsByEventIDResponse)
	err := c.cc.Invoke(ctx, EventService_GetTeamsByEventID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) StartEvent(ctx context.Context, in *StartEventRequest, opts ...grpc.CallOption) (*StartEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartEventResponse)
	err := c.cc.Invoke(ctx, EventService_StartEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) FinishEvent(ctx context.Context, in *FinishEventRequest, opts ...grpc.CallOption) (*FinishEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinishEventResponse)
	err := c.cc.Invoke(ctx, EventService_FinishEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*CreateGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGameResponse)
	err := c.cc.Invoke(ctx, EventService_CreateGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetGameByID(ctx context.Context, in *GetGameByIDRequest, opts ...grpc.CallOption) (*GetGameByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameByIDResponse)
	err := c.cc.Invoke(ctx, EventService_GetGameByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetGamesByEventID(ctx context.Context, in *GetGamesByEventIDRequest, opts ...grpc.CallOption) (*GetGamesByEventIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGamesByEventIDResponse)
	err := c.cc.Invoke(ctx, EventService_GetGamesByEventID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) UpdateGameWinner(ctx context.Context, in *UpdateGameWinnerRequest, opts ...grpc.CallOption) (*UpdateGameWinnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGameWinnerResponse)
	err := c.cc.Invoke(ctx, EventService_UpdateGameWinner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) UpdateGameLoser(ctx context.Context, in *UpdateGameLoserRequest, opts ...grpc.CallOption) (*UpdateGameLoserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGameLoserResponse)
	err := c.cc.Invoke(ctx, EventService_UpdateGameLoser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) FinishGame(ctx context.Context, in *FinishGameRequest, opts ...grpc.CallOption) (*FinishGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinishGameResponse)
	err := c.cc.Invoke(ctx, EventService_FinishGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) AddUserStatsToGame(ctx context.Context, in *AddUserStatsToGameRequest, opts ...grpc.CallOption) (*AddUserStatsToGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddUserStatsToGameResponse)
	err := c.cc.Invoke(ctx, EventService_AddUserStatsToGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetGameStats(ctx context.Context, in *GetGameStatsRequest, opts ...grpc.CallOption) (*GetGameStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameStatsResponse)
	err := c.cc.Invoke(ctx, EventService_GetGameStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetTeamByID(ctx context.Context, in *GetTeamByIDRequest, opts ...grpc.CallOption) (*GetTeamByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTeamByIDResponse)
	err := c.cc.Invoke(ctx, EventService_GetTeamByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) AddUserToTeam(ctx context.Context, in *AddUserToTeamRequest, opts ...grpc.CallOption) (*AddUserToTeamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddUserToTeamResponse)
	err := c.cc.Invoke(ctx, EventService_AddUserToTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) RemoveUserFromTeam(ctx context.Context, in *RemoveUserFromTeamRequest, opts ...grpc.CallOption) (*RemoveUserFromTeamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveUserFromTeamResponse)
	err := c.cc.Invoke(ctx, EventService_RemoveUserFromTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServiceServer is the server API for EventService service.
// All implementations must embed UnimplementedEventServiceServer
// for forward compatibility.
type EventServiceServer interface {
	CreateEvent(context.Context, *CreateEventRequest) (*CreateEventResponse, error)
	GetEventsByCreatorId(context.Context, *GetEventsByCreatorIdRequest) (*GetEventsByCreatorIdResponse, error)
	GetLastEventByCreatorId(context.Context, *GetLastEventByCreatorIdRequest) (*GetLastEventByCreatorIdResponse, error)
	GetEventsByEventName(context.Context, *GetEventsByEventNameRequest) (*GetEventsByEventNameResponse, error)
	GetUnfinishedEventsByUserID(context.Context, *GetUnfinishedEventsByUserIDRequest) (*GetUnfinishedEventsByUserIDResponse, error)
	GetUnfinishedEventsByEventName(context.Context, *GetUnfinishedEventsByEventNameRequest) (*GetUnfinishedEventsByEventNameResponse, error)
	UpdateTimeEvent(context.Context, *UpdateTimeEventRequest) (*UpdateTimeEventResponse, error)
	DeleteEvent(context.Context, *DeleteEventRequest) (*DeleteEventResponse, error)
	JoinToEvent(context.Context, *JoinToEventRequest) (*JoinToEventResponse, error)
	LeaveEvent(context.Context, *LeaveEventRequest) (*LeaveEventResponse, error)
	SetRole(context.Context, *SetRoleRequest) (*SetRoleResponse, error)
	CreateTeamsForEvent(context.Context, *CreateTeamsForEventRequest) (*CreateTeamsForEventResponse, error)
	GetTeamsByEventID(context.Context, *GetTeamsByEventIDRequest) (*GetTeamsByEventIDResponse, error)
	StartEvent(context.Context, *StartEventRequest) (*StartEventResponse, error)
	FinishEvent(context.Context, *FinishEventRequest) (*FinishEventResponse, error)
	CreateGame(context.Context, *CreateGameRequest) (*CreateGameResponse, error)
	GetGameByID(context.Context, *GetGameByIDRequest) (*GetGameByIDResponse, error)
	GetGamesByEventID(context.Context, *GetGamesByEventIDRequest) (*GetGamesByEventIDResponse, error)
	UpdateGameWinner(context.Context, *UpdateGameWinnerRequest) (*UpdateGameWinnerResponse, error)
	UpdateGameLoser(context.Context, *UpdateGameLoserRequest) (*UpdateGameLoserResponse, error)
	FinishGame(context.Context, *FinishGameRequest) (*FinishGameResponse, error)
	AddUserStatsToGame(context.Context, *AddUserStatsToGameRequest) (*AddUserStatsToGameResponse, error)
	GetGameStats(context.Context, *GetGameStatsRequest) (*GetGameStatsResponse, error)
	GetTeamByID(context.Context, *GetTeamByIDRequest) (*GetTeamByIDResponse, error)
	AddUserToTeam(context.Context, *AddUserToTeamRequest) (*AddUserToTeamResponse, error)
	RemoveUserFromTeam(context.Context, *RemoveUserFromTeamRequest) (*RemoveUserFromTeamResponse, error)
	mustEmbedUnimplementedEventServiceServer()
}

// UnimplementedEventServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventServiceServer struct{}

func (UnimplementedEventServiceServer) CreateEvent(context.Context, *CreateEventRequest) (*CreateEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEvent not implemented")
}
func (UnimplementedEventServiceServer) GetEventsByCreatorId(context.Context, *GetEventsByCreatorIdRequest) (*GetEventsByCreatorIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventsByCreatorId not implemented")
}
func (UnimplementedEventServiceServer) GetLastEventByCreatorId(context.Context, *GetLastEventByCreatorIdRequest) (*GetLastEventByCreatorIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLastEventByCreatorId not implemented")
}
func (UnimplementedEventServiceServer) GetEventsByEventName(context.Context, *GetEventsByEventNameRequest) (*GetEventsByEventNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventsByEventName not implemented")
}
func (UnimplementedEventServiceServer) GetUnfinishedEventsByUserID(context.Context, *GetUnfinishedEventsByUserIDRequest) (*GetUnfinishedEventsByUserIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUnfinishedEventsByUserID not implemented")
}
func (UnimplementedEventServiceServer) GetUnfinishedEventsByEventName(context.Context, *GetUnfinishedEventsByEventNameRequest) (*GetUnfinishedEventsByEventNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUnfinishedEventsByEventName not implemented")
}
func (UnimplementedEventServiceServer) UpdateTimeEvent(context.Context, *UpdateTimeEventRequest) (*UpdateTimeEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTimeEvent not implemented")
}
func (UnimplementedEventServiceServer) DeleteEvent(context.Context, *DeleteEventRequest) (*DeleteEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEvent not implemented")
}
func (UnimplementedEventServiceServer) JoinToEvent(context.Context, *JoinToEventRequest) (*JoinToEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinToEvent not implemented")
}
func (UnimplementedEventServiceServer) LeaveEvent(context.Context, *LeaveEventRequest) (*LeaveEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaveEvent not implemented")
}
func (UnimplementedEventServiceServer) SetRole(context.Context, *SetRoleRequest) (*SetRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetRole not implemented")
}
func (UnimplementedEventServiceServer) CreateTeamsForEvent(context.Context, *CreateTeamsForEventRequest) (*CreateTeamsForEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTeamsForEvent not implemented")
}
func (UnimplementedEventServiceServer) GetTeamsByEventID(context.Context, *GetTeamsByEventIDRequest) (*GetTeamsByEventIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTeamsByEventID not implemented")
}
func (UnimplementedEventServiceServer) StartEvent(context.Context, *StartEventRequest) (*StartEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartEvent not implemented")
}
func (UnimplementedEventServiceServer) FinishEvent(context.Context, *FinishEventRequest) (*FinishEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FinishEvent not implemented")
}
func (UnimplementedEventServiceServer) CreateGame(context.Context, *CreateGameRequest) (*CreateGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGame not implemented")
}
func (UnimplementedEventServiceServer) GetGameByID(context.Context, *GetGameByIDRequest) (*GetGameByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGameByID not implemented")
}
func (UnimplementedEventServiceServer) GetGamesByEventID(context.Context, *GetGamesByEventIDRequest) (*GetGamesByEventIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGamesByEventID not implemented")
}
func (UnimplementedEventServiceServer) UpdateGameWinner(context.Context, *UpdateGameWinnerRequest) (*UpdateGameWinnerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGameWinner not implemented")
}
func (UnimplementedEventServiceServer) UpdateGameLoser(context.Context, *UpdateGameLoserRequest) (*UpdateGameLoserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGameLoser not implemented")
}
func (UnimplementedEventServiceServer) FinishGame(context.Context, *FinishGameRequest) (*FinishGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FinishGame not implemented")
}
func (UnimplementedEventServiceServer) AddUserStatsToGame(context.Context, *AddUserStatsToGameRequest) (*AddUserStatsToGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddUserStatsToGame not implemented")
}
func (UnimplementedEventServiceServer) GetGameStats(context.Context, *GetGameStatsRequest) (*GetGameStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGameStats not implemented")
}
func (UnimplementedEventServiceServer) GetTeamByID(context.Context, *GetTeamByIDRequest) (*GetTeamByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTeamByID not implemented")
}
func (UnimplementedEventServiceServer) AddUserToTeam(context.Context, *AddUserToTeamRequest) (*AddUserToTeamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddUserToTeam not implemented")
}
func (UnimplementedEventServiceServer) RemoveUserFromTeam(context.Context, *RemoveUserFromTeamRequest) (*RemoveUserFromTeamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveUserFromTeam not implemented")
}
func (UnimplementedEventServiceServer) mustEmbedUnimplementedEventServiceServer() {}
func (UnimplementedEventServiceServer) testEmbeddedByValue()                      {}

// UnsafeEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventServiceServer will
// result in compilation errors.
type UnsafeEventServiceServer interface {
	mustEmbedUnimplementedEventServiceServer()
}

func RegisterEventServiceServer(s grpc.ServiceRegistrar, srv EventServiceServer) {
	// If the following call panics, it indicates UnimplementedEventServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventService_ServiceDesc, srv)
}

func _EventService_CreateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).CreateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_CreateEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).CreateEvent(ctx, req.(*CreateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetEventsByCreatorId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsByCreatorIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetEventsByCreatorId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetEventsByCreatorId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetEventsByCreatorId(ctx, req.(*GetEventsByCreatorIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetLastEventByCreatorId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLastEventByCreatorIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetLastEventByCreatorId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetLastEventByCreatorId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetLastEventByCreatorId(ctx, req.(*GetLastEventByCreatorIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetEventsByEventName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsByEventNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetEventsByEventName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetEventsByEventName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetEventsByEventName(ctx, req.(*GetEventsByEventNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetUnfinishedEventsByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnfinishedEventsByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetUnfinishedEventsByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetUnfinishedEventsByUserID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetUnfinishedEventsByUserID(ctx, req.(*GetUnfinishedEventsByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetUnfinishedEventsByEventName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnfinishedEventsByEventNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetUnfinishedEventsByEventName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetUnfinishedEventsByEventName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetUnfinishedEventsByEventName(ctx, req.(*GetUnfinishedEventsByEventNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_UpdateTimeEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTimeEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).UpdateTimeEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_UpdateTimeEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).UpdateTimeEvent(ctx, req.(*UpdateTimeEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_DeleteEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).DeleteEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_DeleteEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).DeleteEvent(ctx, req.(*DeleteEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_JoinToEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinToEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).JoinToEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_JoinToEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).JoinToEvent(ctx, req.(*JoinToEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_LeaveEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).LeaveEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_LeaveEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).LeaveEvent(ctx, req.(*LeaveEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_SetRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).SetRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_SetRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).SetRole(ctx, req.(*SetRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_CreateTeamsForEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTeamsForEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).CreateTeamsForEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_CreateTeamsForEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).CreateTeamsForEvent(ctx, req.(*CreateTeamsForEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetTeamsByEventID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeamsByEventIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetTeamsByEventID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetTeamsByEventID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetTeamsByEventID(ctx, req.(*GetTeamsByEventIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_StartEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).StartEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_StartEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).StartEvent(ctx, req.(*StartEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_FinishEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).FinishEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_FinishEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).FinishEvent(ctx, req.(*FinishEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_CreateGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).CreateGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_CreateGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).CreateGame(ctx, req.(*CreateGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetGameByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetGameByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetGameByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetGameByID(ctx, req.(*GetGameByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetGamesByEventID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGamesByEventIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetGamesByEventID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetGamesByEventID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetGamesByEventID(ctx, req.(*GetGamesByEventIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_UpdateGameWinner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGameWinnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).UpdateGameWinner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_UpdateGameWinner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).UpdateGameWinner(ctx, req.(*UpdateGameWinnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_UpdateGameLoser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGameLoserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).UpdateGameLoser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_UpdateGameLoser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).UpdateGameLoser(ctx, req.(*UpdateGameLoserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_FinishGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).FinishGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_FinishGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).FinishGame(ctx, req.(*FinishGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_AddUserStatsToGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserStatsToGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).AddUserStatsToGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_AddUserStatsToGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).AddUserStatsToGame(ctx, req.(*AddUserStatsToGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetGameStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetGameStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetGameStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetGameStats(ctx, req.(*GetGameStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetTeamByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeamByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetTeamByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetTeamByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetTeamByID(ctx, req.(*GetTeamByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_AddUserToTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserToTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).AddUserToTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_AddUserToTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).AddUserToTeam(ctx, req.(*AddUserToTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_RemoveUserFromTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveUserFromTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).RemoveUserFromTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_RemoveUserFromTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).RemoveUserFromTeam(ctx, req.(*RemoveUserFromTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventService_ServiceDesc is the grpc.ServiceDesc for EventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "event.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEvent",
			Handler:    _EventService_CreateEvent_Handler,
		},
		{
			MethodName: "GetEventsByCreatorId",
			Handler:    _EventService_GetEventsByCreatorId_Handler,
		},
		{
			MethodName: "GetLastEventByCreatorId",
			Handler:    _EventService_GetLastEventByCreatorId_Handler,
		},
		{
			MethodName: "GetEventsByEventName",
			Handler:    _EventService_GetEventsByEventName_Handler,
		},
		{
			MethodName: "GetUnfinishedEventsByUserID",
			Handler:    _EventService_GetUnfinishedEventsByUserID_Handler,
		},
		{
			MethodName: "GetUnfinishedEventsByEventName",
			Handler:    _EventService_GetUnfinishedEventsByEventName_Handler,
		},
		{
			MethodName: "UpdateTimeEvent",
			Handler:    _EventService_UpdateTimeEvent_Handler,
		},
		{
			MethodName: "DeleteEvent",
			Handler:    _EventService_DeleteEvent_Handler,
		},
		{
			MethodName: "JoinToEvent",
			Handler:    _EventService_JoinToEvent_Handler,
		},
		{
			MethodName: "LeaveEvent",
			Handler:    _EventService_LeaveEvent_Handler,
		},
		{
			MethodName: "SetRole",
			Handler:    _EventService_SetRole_Handler,
		},
		{
			MethodName: "CreateTeamsForEvent",
			Handler:    _EventService_CreateTeamsForEvent_Handler,
		},
		{
			MethodName: "GetTeamsByEventID",
			Handler:    _EventService_GetTeamsByEventID_Handler,
		},
		{
			MethodName: "StartEvent",
			Handler:    _EventService_StartEvent_Handler,
		},
		{
			MethodName: "FinishEvent",
			Handler:    _EventService_FinishEvent_Handler,
		},
		{
			MethodName: "CreateGame",
			Handler:    _EventService_CreateGame_Handler,
		},
		{
			MethodName: "GetGameByID",
			Handler:    _EventService_GetGameByID_Handler,
		},
		{
			MethodName: "GetGamesByEventID",
			Handler:    _EventService_GetGamesByEventID_Handler,
		},
		{
			MethodName: "UpdateGameWinner",
			Handler:    _EventService_UpdateGameWinner_Handler,
		},
		{
			MethodName: "UpdateGameLoser",
			Handler:    _EventService_UpdateGameLoser_Handler,
		},
		{
			MethodName: "FinishGame",
			Handler:    _EventService_FinishGame_Handler,
		},
		{
			MethodName: "AddUserStatsToGame",
			Handler:    _EventService_AddUserStatsToGame_Handler,
		},
		{
			MethodName: "GetGameStats",
			Handler:    _EventService_GetGameStats_Handler,
		},
		{
			MethodName: "GetTeamByID",
			Handler:    _EventService_GetTeamByID_Handler,
		},
		{
			MethodName: "AddUserToTeam",
			Handler:    _EventService_AddUserToTeam_Handler,
		},
		{
			MethodName: "RemoveUserFromTeam",
			Handler:    _EventService_RemoveUserFromTeam_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event.proto",
}
