CREATE TABLE users (
   id UUID PRIMARY KEY,
   steam_id VARCHAR(20) UNIQUE NOT NULL,
   display_name VARCHAR(100) NOT NULL,
   avatar_url VARCHAR(255),
   created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
   last_login_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_steam_id ON users(steam_id);