CREATE TABLE vps_hosting (
    id UUID PRIMARY KEY NOT NULL,
    hosting VARCHAR(255),
    api_token VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);